// examples/react/src/screens/email-link-auth-screen.tsx
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

"use client";

import { EmailLinkAuthScreen } from "@firebase-oss/ui-react";
import { useNavigate } from "react-router";

export default function EmailLinkAuthScreenPage() {
  const navigate = useNavigate();

  return (
    <EmailLinkAuthScreen
      onEmailSent={() => {
        alert("Email has been sent");
      }}
      onSignIn={() => {
        navigate("/");
      }}
    />
  );
}

// examples/angular/src/app/screens/email-link-auth-screen.ts
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, inject } from "@angular/core";
import { CommonModule } from "@angular/common";
import { EmailLinkAuthScreenComponent } from "@firebase-oss/ui-angular";
import { Router } from "@angular/router";

@Component({
  selector: "app-email-link-auth-screen",
  standalone: true,
  imports: [CommonModule, EmailLinkAuthScreenComponent],
  template: ` <fui-email-link-auth-screen (emailSent)="onEmailSent()" (signIn)="onSignIn()" />`,
  styles: [],
})
export class EmailLinkAuthScreenWrapperComponent {
  private router = inject(Router);

  onEmailSent() {
    alert("email sent - please check your email");
  }

  onSignIn() {
    this.router.navigate(["/"]);
  }
}
