// examples/shadcn/src/screens/phone-auth-screen.tsx
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

"use client";

import { PhoneAuthScreen } from "@/components/phone-auth-screen";
import { useNavigate } from "react-router";

export default function PhoneAuthScreenPage() {
  const navigate = useNavigate();

  return (
    <PhoneAuthScreen
      onSignIn={() => {
        navigate("/");
      }}
    />
  );
}

// examples/angular/src/app/screens/phone-auth-screen.ts
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, inject } from "@angular/core";
import { CommonModule } from "@angular/common";
import { PhoneAuthScreenComponent } from "@firebase-oss/ui-angular";
import { Router } from "@angular/router";

@Component({
  selector: "app-phone-auth-screen",
  standalone: true,
  imports: [CommonModule, PhoneAuthScreenComponent],
  template: ` <fui-phone-auth-screen (signIn)="onSignIn()" />`,
  styles: [],
})
export class PhoneAuthScreenWrapperComponent {
  private router = inject(Router);

  onSignIn() {
    this.router.navigate(["/"]);
  }
}
