// examples/shadcn/src/screens/sign-up-auth-screen.tsx
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

"use client";

import { SignUpAuthScreen } from "@/components/sign-up-auth-screen";
import { useNavigate } from "react-router";

export default function SignUpAuthScreenPage() {
  const navigate = useNavigate();
  return (
    <SignUpAuthScreen
      onSignUp={() => {
        navigate("/");
      }}
    />
  );
}

// examples/angular/src/app/screens/sign-up-auth-screen.ts
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, inject } from "@angular/core";
import { CommonModule } from "@angular/common";
import { SignUpAuthScreenComponent } from "@firebase-oss/ui-angular";

@Component({
  selector: "app-sign-up-auth-screen",
  standalone: true,
  imports: [CommonModule, SignUpAuthScreenComponent],
  template: ` <fui-sign-up-auth-screen (signUp)="onSignUp()" />`,
  styles: [],
})
export class SignUpAuthScreenWrapperComponent {
  private router = inject(Router);

  onSignUp() {
    this.router.navigate(["/"]);
  }
}
