// examples/react/src/screens/sign-up-auth-screen-w-handlers.tsx
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

"use client";

import { SignUpAuthScreen } from "@firebase-oss/ui-react";
import { useNavigate } from "react-router";

export default function SignUpAuthScreenWithHandlersPage() {
  const navigate = useNavigate();

  return (
    <SignUpAuthScreen
      onSignInClick={() => {
        navigate("/screens/sign-in-auth-screen");
      }}
      onSignUp={() => {
        navigate("/");
      }}
    />
  );
}

// examples/angular/src/app/screens/sign-up-auth-screen-w-handlers.ts
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, inject } from "@angular/core";
import { CommonModule } from "@angular/common";
import { Router } from "@angular/router";
import { SignUpAuthScreenComponent } from "@firebase-oss/ui-angular";

@Component({
  selector: "app-sign-up-auth-screen-w-handlers",
  standalone: true,
  imports: [CommonModule, SignUpAuthScreenComponent],
  template: `<fui-sign-up-auth-screen (signIn)="goToSignIn()" (signUp)="onSignUp()" />`,
  styles: [],
})
export class SignUpAuthScreenWithHandlersComponent {
  private router = inject(Router);

  goToSignIn() {
    this.router.navigate(["/screens/sign-in-auth-screen"]);
  }

  onSignUp() {
    this.router.navigate(["/"]);
  }
}
