// packages/firebaseui-angular/src/lib/auth/forms/phone-form/phone-form.component.ts
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {
  Component,
  inject,
  Input,
  OnDestroy,
  OnInit,
  ViewChild,
  ElementRef,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { injectForm, TanStackField } from '@tanstack/angular-form';
import { FirebaseUI } from '../../../provider';
import {
  Auth,
  ConfirmationResult,
  RecaptchaVerifier,
} from '@angular/fire/auth';
import { map } from 'rxjs/operators';
import { ButtonComponent } from '../../../components/button/button.component';
import { TermsAndPrivacyComponent } from '../../../components/terms-and-privacy/terms-and-privacy.component';
import { CountrySelectorComponent } from '../../../components/country-selector/country-selector.component';
import {
  CountryData,
  countryData,
  createPhoneFormSchema,
  FirebaseUIError,
  formatPhoneNumberWithCountry,
  confirmPhoneNumber,
  signInWithPhoneNumber,
} from '@firebase-ui/core';
import { interval, Subscription, firstValueFrom } from 'rxjs';
import { Router } from '@angular/router';
import { takeWhile } from 'rxjs/operators';
import { z } from 'zod';

@Component({
  selector: 'fui-phone-number-form',
  standalone: true,
  imports: [
    CommonModule,
    TanStackField,
    ButtonComponent,
    TermsAndPrivacyComponent,
    CountrySelectorComponent,
  ],
  template: `
    <form (submit)="handleSubmit($event)" class="fui-form">
      <fieldset>
        <ng-container
          [tanstackField]="form"
          name="phoneNumber"
          #phoneNumber="field"
        >
          <label [for]="phoneNumber.api.name">
            <span>{{ phoneNumberLabel | async }}</span>
            <div class="fui-phone-input">
              <fui-country-selector
                [value]="selectedCountry"
                (onChange)="handleCountryChange($event)"
                className="fui-phone-input__country-selector"
              ></fui-country-selector>
              <input
                type="tel"
                [id]="phoneNumber.api.name"
                [name]="phoneNumber.api.name"
                [value]="phoneNumber.api.state.value"
                (blur)="phoneNumber.api.handleBlur()"
                (input)="
                  phoneNumber.api.handleChange($any($event).target.value)
                "
                [attr.aria-invalid]="!!phoneNumber.api.state.meta.errors.length"
                class="fui-phone-input__number-input"
              />
            </div>
            <span
              role="alert"
              aria-live="polite"
              class="fui-form__error"
              *ngIf="!!phoneNumber.api.state.meta.errors.length"
            >
              {{ phoneNumber.api.state.meta.errors.join(', ') }}
            </span>
          </label>
        </ng-container>
      </fieldset>

      <fieldset>
        <div class="fui-recaptcha-container" #recaptchaContainer></div>
      </fieldset>

      <fui-terms-and-privacy></fui-terms-and-privacy>

      <fieldset>
        <fui-button type="submit" [disabled]="!recaptchaVerifier">
          {{ sendCodeLabel | async }}
        </fui-button>
        <div class="fui-form__error" *ngIf="formError">{{ formError }}</div>
      </fieldset>
    </form>
  `,
})
export class PhoneNumberFormComponent implements OnInit, OnDestroy {
  private ui = inject(FirebaseUI);

  @Input() onSubmit!: (phoneNumber: string) => Promise<void>;
  @Input() formError: string | null = null;
  @Input() showTerms = true;
  @ViewChild('recaptchaContainer', { static: true })
  recaptchaContainer!: ElementRef<HTMLDivElement>;

  recaptchaVerifier: RecaptchaVerifier | null = null;
  selectedCountry: CountryData = countryData[0];
  private formSchema: any;
  private config: any;

  form = injectForm({
    defaultValues: {
      phoneNumber: '',
    },
  });

  async ngOnInit() {
    try {
      this.config = await firstValueFrom(this.ui.config());

      this.formSchema = createPhoneFormSchema(this.config?.translations).pick({
        phoneNumber: true,
      });

      this.form.update({
        validators: {
          onSubmit: this.formSchema,
          onBlur: this.formSchema,
        },
      });

      await this.initRecaptcha();
    } catch (error) {
      console.error(error);
    }
  }

  ngOnDestroy() {
    if (this.recaptchaVerifier) {
      this.recaptchaVerifier.clear();
      this.recaptchaVerifier = null;
    }
  }

  async initRecaptcha() {
    const verifier = new RecaptchaVerifier(
      (await firstValueFrom(this.ui.config())).getAuth(),
      this.recaptchaContainer.nativeElement,
      {
        size: this.config?.recaptchaMode ?? 'normal',
      },
    );
    this.recaptchaVerifier = verifier;
  }

  async handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    event.stopPropagation();

    const phoneNumber = this.form.state.values.phoneNumber;

    if (!phoneNumber) {
      return;
    }

    this.submitPhoneNumber(phoneNumber);
  }

  async submitPhoneNumber(phoneNumber: string) {
    try {
      // Validate phoneNumber
      const validationResult = this.formSchema.safeParse({
        phoneNumber,
      });

      if (!validationResult.success) {
        const validationErrors = validationResult.error.format();

        if (validationErrors.phoneNumber?._errors?.length) {
          // We can't set formError directly since it's an input, so we need to call the parent
          await this.onSubmit(
            'VALIDATION_ERROR:' + validationErrors.phoneNumber._errors[0],
          );
          return;
        }

        await this.onSubmit('VALIDATION_ERROR:Invalid phone number');
        return;
      }

      // Format number and submit
      const formattedNumber = formatPhoneNumberWithCountry(
        phoneNumber,
        this.selectedCountry.dialCode,
      );
      await this.onSubmit(formattedNumber);
    } catch (error) {
      console.error(error);
    }
  }

  handleCountryChange(country: CountryData) {
    this.selectedCountry = country;
  }

  get phoneNumberLabel() {
    return this.ui.translation('labels', 'phoneNumber');
  }

  get sendCodeLabel() {
    return this.ui.translation('labels', 'sendCode');
  }
}

@Component({
  selector: 'fui-verification-form',
  standalone: true,
  imports: [
    CommonModule,
    TanStackField,
    ButtonComponent,
    TermsAndPrivacyComponent,
  ],
  template: `
    <form (submit)="handleSubmit($event)" class="fui-form">
      <fieldset>
        <ng-container
          [tanstackField]="form"
          name="verificationCode"
          #verificationCode="field"
        >
          <label [for]="verificationCode.api.name">
            <span>{{ verificationCodeLabel | async }}</span>
            <input
              type="text"
              [id]="verificationCode.api.name"
              [name]="verificationCode.api.name"
              [value]="verificationCode.api.state.value"
              (blur)="verificationCode.api.handleBlur()"
              (input)="
                verificationCode.api.handleChange($any($event).target.value)
              "
              [attr.aria-invalid]="
                !!verificationCode.api.state.meta.errors.length
              "
            />
            <span
              role="alert"
              aria-live="polite"
              class="fui-form__error"
              *ngIf="!!verificationCode.api.state.meta.errors.length"
            >
              {{ verificationCode.api.state.meta.errors.join(', ') }}
            </span>
          </label>
        </ng-container>
      </fieldset>

      <fieldset>
        <div class="fui-recaptcha-container" #recaptchaContainer></div>
      </fieldset>

      <ng-container *ngIf="showTerms">
        <fui-terms-and-privacy></fui-terms-and-privacy>
      </ng-container>

      <fieldset>
        <fui-button type="submit">
          {{ verifyCodeLabel | async }}
        </fui-button>
        <fui-button
          type="button"
          (click)="onResend()"
          [disabled]="isResending || !canResend"
          variant="secondary"
        >
          <ng-container *ngIf="isResending">
            {{ sendingLabel | async }}
          </ng-container>
          <ng-container *ngIf="!isResending && !canResend">
            {{ resendCodeLabel | async }} ({{ timeLeft }}s)
          </ng-container>
          <ng-container *ngIf="!isResending && canResend">
            {{ resendCodeLabel | async }}
          </ng-container>
        </fui-button>
        <div class="fui-form__error" *ngIf="formError">{{ formError }}</div>
      </fieldset>

      <!-- Back to sign in button removed to match React implementation -->
    </form>
  `,
})
export class VerificationFormComponent implements OnInit, OnDestroy {
  private ui = inject(FirebaseUI);

  @Input() onSubmit!: (code: string) => Promise<void>;
  @Input() onResend!: () => Promise<void>;
  @Input() formError: string | null = null;
  @Input() showTerms = false;
  @Input() isResending = false;
  @Input() canResend = false;
  @Input() timeLeft = 0;
  @ViewChild('recaptchaContainer', { static: true })
  recaptchaContainer!: ElementRef<HTMLDivElement>;

  private formSchema: any;
  private config: any;

  form = injectForm({
    defaultValues: {
      verificationCode: '',
    },
  });

  async ngOnInit() {
    try {
      this.config = await firstValueFrom(this.ui.config());

      // Create schema once
      this.formSchema = createPhoneFormSchema(this.config?.translations).pick({
        verificationCode: true,
      });

      this.form.update({
        validators: {
          onSubmit: this.formSchema,
          onBlur: this.formSchema,
        },
      });
    } catch (error) {
      console.error(error);
    }
  }

  ngOnDestroy() {}

  async handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    event.stopPropagation();

    const code = this.form.state.values.verificationCode;

    if (!code) {
      return;
    }

    await this.verifyCode(code);
  }

  async verifyCode(code: string) {
    try {
      const validationResult = this.formSchema.safeParse({
        verificationCode: code,
      });

      if (!validationResult.success) {
        const validationErrors = validationResult.error.format();

        if (validationErrors.verificationCode?._errors?.length) {
          await this.onSubmit(
            'VALIDATION_ERROR:' + validationErrors.verificationCode._errors[0],
          );
          return;
        }

        await this.onSubmit('VALIDATION_ERROR:Invalid verification code');
        return;
      }

      await this.onSubmit(code);
    } catch (error) {
      console.error(error);
    }
  }

  get verificationCodeLabel() {
    return this.ui.translation('labels', 'verificationCode');
  }

  get verifyCodeLabel() {
    return this.ui.translation('labels', 'verifyCode');
  }

  get resendCodeLabel() {
    return this.ui.translation('labels', 'resendCode');
  }

  get sendingLabel() {
    return this.ui.translation('labels', 'sending');
  }
}

@Component({
  selector: 'fui-phone-form',
  standalone: true,
  imports: [CommonModule, PhoneNumberFormComponent, VerificationFormComponent],
  template: `
    <div class="fui-form-container">
      <ng-container *ngIf="confirmationResult; else phoneNumberForm">
        <fui-verification-form
          [onSubmit]="handleVerificationSubmit.bind(this)"
          [onResend]="handleResend.bind(this)"
          [formError]="formError"
          [showTerms]="false"
          [isResending]="isResending"
          [canResend]="canResend"
          [timeLeft]="timeLeft"
        ></fui-verification-form>
      </ng-container>
      <ng-template #phoneNumberForm>
        <fui-phone-number-form
          [onSubmit]="handlePhoneSubmit.bind(this)"
          [formError]="formError"
          [showTerms]="true"
        ></fui-phone-number-form>
      </ng-template>
    </div>
  `,
})
export class PhoneFormComponent implements OnInit, OnDestroy {
  private ui = inject(FirebaseUI);
  private config: any;

  @Input() resendDelay = 30;

  formError: string | null = null;
  confirmationResult: ConfirmationResult | null = null;
  recaptchaVerifier: RecaptchaVerifier | null = null;
  phoneNumber = '';
  isResending = false;
  timeLeft = 0;
  canResend = false;
  timerSubscription: Subscription | null = null;

  async ngOnInit() {
    try {
      this.config = await firstValueFrom(this.ui.config());
    } catch (error) {
      console.error(error);
    }
  }

  ngOnDestroy() {
    if (this.timerSubscription) {
      this.timerSubscription.unsubscribe();
    }
  }

  async handlePhoneSubmit(number: string): Promise<void> {
    this.formError = null;

    if (number.startsWith('VALIDATION_ERROR:')) {
      this.formError = number.substring('VALIDATION_ERROR:'.length);
      return;
    }

    try {
      if (!this.recaptchaVerifier) {
        throw new Error('ReCAPTCHA not initialized');
      }

      const result = await signInWithPhoneNumber(
        await firstValueFrom(this.ui.config()),
        number,
        this.recaptchaVerifier,
      );

      this.phoneNumber = number;
      this.confirmationResult = result;
      this.startTimer();
    } catch (error) {
      if (error instanceof FirebaseUIError) {
        this.formError = error.message;
        return;
      }
      console.error(error);
      this.formError = await firstValueFrom(
        this.ui.translation('errors', 'unknownError'),
      );
    }
  }

  async handleResend(): Promise<void> {
    if (this.isResending || !this.canResend || !this.phoneNumber) {
      return;
    }

    this.isResending = true;
    this.formError = null;

    try {
      if (this.recaptchaVerifier) {
        this.recaptchaVerifier.clear();
      }

      // We need to get the recaptcha container from the verification form
      // This is a bit hacky, but it works for now
      const recaptchaContainer = document.querySelector(
        '.fui-recaptcha-container',
      ) as HTMLDivElement;
      if (!recaptchaContainer) {
        throw new Error('ReCAPTCHA container not found');
      }

      const verifier = new RecaptchaVerifier(
        (await firstValueFrom(this.ui.config())).getAuth(),
        recaptchaContainer,
        {
          size: this.config?.recaptchaMode ?? 'normal',
        },
      );
      this.recaptchaVerifier = verifier;

      const result = await signInWithPhoneNumber(
        await firstValueFrom(this.ui.config()),
        this.phoneNumber,
        verifier,
      );

      this.confirmationResult = result;
      this.startTimer();
    } catch (error) {
      if (error instanceof FirebaseUIError) {
        this.formError = error.message;
      } else {
        console.error(error);
        this.ui.translation('errors', 'unknownError').subscribe((message) => {
          this.formError = message;
        });
      }
    } finally {
      this.isResending = false;
    }
  }

  async handleVerificationSubmit(code: string): Promise<void> {
    if (code.startsWith('VALIDATION_ERROR:')) {
      this.formError = code.substring('VALIDATION_ERROR:'.length);
      return;
    }

    if (!this.confirmationResult) {
      throw new Error('Confirmation result not initialized');
    }

    this.formError = null;

    try {
      await confirmPhoneNumber(
        await firstValueFrom(this.ui.config()),
        this.confirmationResult,
        code,
      );
    } catch (error) {
      if (error instanceof FirebaseUIError) {
        this.formError = error.message;
        return;
      }
      console.error(error);
      this.formError = await firstValueFrom(
        this.ui.translation('errors', 'unknownError'),
      );
    }
  }

  startTimer() {
    if (this.timerSubscription) {
      this.timerSubscription.unsubscribe();
    }

    this.timeLeft = this.resendDelay;
    this.canResend = false;

    this.timerSubscription = interval(1000)
      .pipe(takeWhile(() => this.timeLeft > 0))
      .subscribe(() => {
        this.timeLeft--;
        if (this.timeLeft === 0) {
          this.canResend = true;
          if (this.timerSubscription) {
            this.timerSubscription.unsubscribe();
          }
        }
      });
  }
}

// packages/firebaseui-react/src/auth/forms/phone-form.tsx
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

"use client";

import {
  confirmPhoneNumber,
  CountryData,
  countryData,
  createPhoneFormSchema,
  FirebaseUIError,
  formatPhoneNumberWithCountry,
  getTranslation,
  signInWithPhoneNumber,
} from "@invertase/firebaseui-core";
import { useForm } from "@tanstack/react-form";
import { ConfirmationResult, RecaptchaVerifier } from "firebase/auth";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { z } from "zod";
import { useAuth, useUI } from "~/hooks";
import { Button } from "../../components/button";
import { CountrySelector } from "../../components/country-selector";
import { FieldInfo } from "../../components/field-info";
import { Policies } from "../../components/policies";

interface PhoneNumberFormProps {
  onSubmit: (phoneNumber: string) => Promise<void>;
  formError: string | null;
  recaptchaVerifier: RecaptchaVerifier | null;
  recaptchaContainerRef: React.RefObject<HTMLDivElement | null>;
}

function PhoneNumberForm({
  onSubmit,
  formError,
  recaptchaVerifier,
  recaptchaContainerRef,
}: PhoneNumberFormProps) {
  const ui = useUI();

  const [selectedCountry, setSelectedCountry] = useState<CountryData>(
    countryData[0]
  );
  const [firstValidationOccured, setFirstValidationOccured] = useState(false);

  const phoneFormSchema = useMemo(
    () =>
      createPhoneFormSchema(ui.translations).pick({
        phoneNumber: true,
      }),
    [ui.translations]
  );

  const phoneForm = useForm<z.infer<typeof phoneFormSchema>>({
    defaultValues: {
      phoneNumber: "",
    },
    validators: {
      onBlur: phoneFormSchema,
      onSubmit: phoneFormSchema,
    },
    onSubmit: async ({ value }) => {
      const formattedNumber = formatPhoneNumberWithCountry(
        value.phoneNumber,
        selectedCountry.dialCode
      );
      await onSubmit(formattedNumber);
    },
  });

  return (
    <form
      className="fui-form"
      onSubmit={async (e) => {
        e.preventDefault();
        e.stopPropagation();
        await phoneForm.handleSubmit();
      }}
    >
      <fieldset>
        <phoneForm.Field
          name="phoneNumber"
          children={(field) => (
            <>
              <label htmlFor={field.name}>
                <span>{getTranslation(ui, "labels", "phoneNumber")}</span>
                <div className="fui-phone-input">
                  <CountrySelector
                    value={selectedCountry}
                    onChange={setSelectedCountry}
                    className="fui-phone-input__country-selector"
                  />
                  <input
                    aria-invalid={
                      field.state.meta.isTouched &&
                      field.state.meta.errors.length > 0
                    }
                    id={field.name}
                    name={field.name}
                    type="tel"
                    value={field.state.value}
                    onBlur={() => {
                      setFirstValidationOccured(true);
                      field.handleBlur();
                    }}
                    onInput={(e) => {
                      field.handleChange((e.target as HTMLInputElement).value);
                      if (firstValidationOccured) {
                        field.handleBlur();
                        phoneForm.update();
                      }
                    }}
                    className="fui-phone-input__number-input"
                  />
                </div>
                <FieldInfo field={field} />
              </label>
            </>
          )}
        />
      </fieldset>

      <fieldset>
        <div className="fui-recaptcha-container" ref={recaptchaContainerRef} />
      </fieldset>

      <Policies />

      <fieldset>
        <Button
          type="submit"
          disabled={!recaptchaVerifier || ui.state !== "idle"}
        >
          {getTranslation(ui, "labels", "sendCode")}
        </Button>
        {formError && <div className="fui-form__error">{formError}</div>}
      </fieldset>
    </form>
  );
}

function useResendTimer(initialDelay: number) {
  const [timeLeft, setTimeLeft] = useState(0);
  const [isActive, setIsActive] = useState(false);
  const timerRef = useRef<number>(0);

  useEffect(() => {
    return () => {
      if (timerRef.current) {
        clearInterval(timerRef.current);
      }
    };
  }, [initialDelay]);

  const startTimer = useCallback(() => {
    if (timerRef.current) {
      clearInterval(timerRef.current);
    }

    setTimeLeft(initialDelay);
    setIsActive(true);

    timerRef.current = window.setInterval(() => {
      setTimeLeft((prev) => {
        const next = prev <= 1 ? 0 : prev - 1;
        if (prev <= 1) {
          if (timerRef.current) {
            clearInterval(timerRef.current);
          }
          setIsActive(false);
        }
        return next;
      });
    }, 1000);
  }, [initialDelay]);

  const canResend = !isActive && timeLeft === 0;

  return { timeLeft, canResend, startTimer };
}

interface VerificationFormProps {
  onSubmit: (code: string) => Promise<void>;
  onResend: () => Promise<void>;
  formError: string | null;
  isResending: boolean;
  canResend: boolean;
  timeLeft: number;
  recaptchaContainerRef: React.RefObject<HTMLDivElement | null>;
}

function VerificationForm({
  onSubmit,
  onResend,
  formError,
  isResending,
  canResend,
  timeLeft,
  recaptchaContainerRef,
}: VerificationFormProps) {
  const ui = useUI();

  const [firstValidationOccured, setFirstValidationOccured] = useState(false);

  const verificationFormSchema = useMemo(
    () =>
      createPhoneFormSchema(ui.translations).pick({
        verificationCode: true,
      }),
    [ui.translations]
  );

  const verificationForm = useForm<z.infer<typeof verificationFormSchema>>({
    defaultValues: {
      verificationCode: "",
    },
    validators: {
      onBlur: verificationFormSchema,
      onSubmit: verificationFormSchema,
    },
    onSubmit: async ({ value }) => {
      await onSubmit(value.verificationCode);
    },
  });

  return (
    <form
      className="fui-form"
      onSubmit={async (e) => {
        e.preventDefault();
        e.stopPropagation();
        await verificationForm.handleSubmit();
      }}
    >
      <fieldset>
        <verificationForm.Field
          name="verificationCode"
          children={(field) => (
            <>
              <label htmlFor={field.name}>
                <span>{getTranslation(ui, "labels", "verificationCode")}</span>
                <input
                  aria-invalid={
                    field.state.meta.isTouched &&
                    field.state.meta.errors.length > 0
                  }
                  id={field.name}
                  name={field.name}
                  type="text"
                  value={field.state.value}
                  onBlur={() => {
                    setFirstValidationOccured(true);
                    field.handleBlur();
                  }}
                  onInput={(e) => {
                    field.handleChange((e.target as HTMLInputElement).value);
                    if (firstValidationOccured) {
                      field.handleBlur();
                      verificationForm.update();
                    }
                  }}
                />
                <FieldInfo field={field} />
              </label>
            </>
          )}
        />
      </fieldset>

      <fieldset>
        <div className="fui-recaptcha-container" ref={recaptchaContainerRef} />
      </fieldset>

      <Policies />

      <fieldset>
        <Button type="submit" disabled={ui.state !== "idle"}>
          {getTranslation(ui, "labels", "verifyCode")}
        </Button>
        <Button
          type="button"
          disabled={isResending || !canResend || ui.state !== "idle"}
          onClick={onResend}
          variant="secondary"
        >
          {isResending
            ? getTranslation(ui, "labels", "sending")
            : !canResend
              ? `${getTranslation(ui, "labels", "resendCode")} (${timeLeft}s)`
              : getTranslation(ui, "labels", "resendCode")}
        </Button>
        {formError && <div className="fui-form__error">{formError}</div>}
      </fieldset>
    </form>
  );
}

export interface PhoneFormProps {
  resendDelay?: number;
}

export function PhoneForm({ resendDelay = 30 }: PhoneFormProps) {
  const ui = useUI();
  const auth = useAuth(ui);

  const [formError, setFormError] = useState<string | null>(null);
  const [confirmationResult, setConfirmationResult] =
    useState<ConfirmationResult | null>(null);
  const [recaptchaVerifier, setRecaptchaVerifier] =
    useState<RecaptchaVerifier | null>(null);
  const [phoneNumber, setPhoneNumber] = useState<string>("");
  const [isResending, setIsResending] = useState(false);
  const recaptchaContainerRef = useRef<HTMLDivElement | null>(null);
  const { timeLeft, canResend, startTimer } = useResendTimer(resendDelay);

  useEffect(() => {
    if (!recaptchaContainerRef.current) return;

    const verifier = new RecaptchaVerifier(
      auth,
      recaptchaContainerRef.current,
      {
        size: ui.recaptchaMode ?? "normal",
      }
    );

    setRecaptchaVerifier(verifier);

    return () => {
      verifier.clear();
      setRecaptchaVerifier(null);
    };
  }, [auth, ui.recaptchaMode]);

  const handlePhoneSubmit = async (number: string) => {
    setFormError(null);
    try {
      if (!recaptchaVerifier) {
        throw new Error("ReCAPTCHA not initialized");
      }

      const result = await signInWithPhoneNumber(ui, number, recaptchaVerifier);
      setPhoneNumber(number);
      setConfirmationResult(result);
      startTimer();
    } catch (error) {
      if (error instanceof FirebaseUIError) {
        setFormError(error.message);
        return;
      }
      console.error(error);
      setFormError(getTranslation(ui, "errors", "unknownError"));
    }
  };

  const handleResend = async () => {
    if (
      isResending ||
      !canResend ||
      !phoneNumber ||
      !recaptchaContainerRef.current
    ) {
      return;
    }

    setIsResending(true);
    setFormError(null);

    try {
      if (recaptchaVerifier) {
        recaptchaVerifier.clear();
      }

      const verifier = new RecaptchaVerifier(
        auth,
        recaptchaContainerRef.current,
        {
          size: ui.recaptchaMode ?? "normal",
        }
      );
      setRecaptchaVerifier(verifier);

      const result = await signInWithPhoneNumber(ui, phoneNumber, verifier);
      setConfirmationResult(result);
      startTimer();
    } catch (error) {
      if (error instanceof FirebaseUIError) {
        setFormError(error.message);
      } else {
        console.error(error);
        setFormError(getTranslation(ui, "errors", "unknownError"));
      }
    } finally {
      setIsResending(false);
    }
  };

  const handleVerificationSubmit = async (code: string) => {
    if (!confirmationResult) {
      throw new Error("Confirmation result not initialized");
    }

    setFormError(null);

    try {
      await confirmPhoneNumber(ui, confirmationResult, code);
    } catch (error) {
      if (error instanceof FirebaseUIError) {
        setFormError(error.message);
        return;
      }
      console.error(error);
      setFormError(getTranslation(ui, "errors", "unknownError"));
    }
  };

  return (
    <div className="fui-form-container">
      {confirmationResult ? (
        <VerificationForm
          onSubmit={handleVerificationSubmit}
          onResend={handleResend}
          formError={formError}
          isResending={isResending}
          canResend={canResend}
          timeLeft={timeLeft}
          recaptchaContainerRef={recaptchaContainerRef}
        />
      ) : (
        <PhoneNumberForm
          onSubmit={handlePhoneSubmit}
          formError={formError}
          recaptchaVerifier={recaptchaVerifier}
          recaptchaContainerRef={recaptchaContainerRef}
        />
      )}
    </div>
  );
}
