// packages/react/src/auth/forms/sign-up-auth-form.tsx
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

"use client";

import {
  FirebaseUIError,
  getTranslation,
  createUserWithEmailAndPassword,
  hasBehavior,
} from "@invertase/firebaseui-core";
import type { UserCredential } from "firebase/auth";
import { useSignUpAuthFormSchema, useUI } from "~/hooks";
import { form } from "~/components/form";
import { Policies } from "~/components/policies";
import { useCallback } from "react";
import { type z } from "zod";

export function useRequireDisplayName() {
  const ui = useUI();
  return hasBehavior(ui, "requireDisplayName");
}

export type SignUpAuthFormProps = {
  onSignUp?: (credential: UserCredential) => void;
  onSignInClick?: () => void;
};

export function useSignUpAuthFormAction() {
  const ui = useUI();

  return useCallback(
    async ({ email, password, displayName }: { email: string; password: string; displayName?: string }) => {
      try {
        return await createUserWithEmailAndPassword(ui, email, password, displayName);
      } catch (error) {
        if (error instanceof FirebaseUIError) {
          throw new Error(error.message);
        }

        console.error(error);
        throw new Error(getTranslation(ui, "errors", "unknownError"));
      }
    },
    [ui]
  );
}

export function useSignUpAuthForm(onSuccess?: SignUpAuthFormProps["onSignUp"]) {
  const schema = useSignUpAuthFormSchema();
  const action = useSignUpAuthFormAction();
  const requireDisplayName = useRequireDisplayName();

  return form.useAppForm({
    defaultValues: {
      email: "",
      password: "",
      displayName: requireDisplayName ? "" : undefined,
    } as z.infer<typeof schema>,
    validators: {
      onBlur: schema,
      onSubmitAsync: async ({ value }) => {
        try {
          const credential = await action(value);
          return onSuccess?.(credential);
        } catch (error) {
          return error instanceof Error ? error.message : String(error);
        }
      },
    },
  });
}

export function SignUpAuthForm({ onSignInClick, onSignUp }: SignUpAuthFormProps) {
  const ui = useUI();
  const form = useSignUpAuthForm(onSignUp);
  const requireDisplayName = useRequireDisplayName();

  return (
    <form
      className="fui-form"
      onSubmit={async (e) => {
        e.preventDefault();
        e.stopPropagation();
        await form.handleSubmit();
      }}
    >
      <form.AppForm>
        {requireDisplayName ? (
          <fieldset>
            <form.AppField name="displayName">
              {(field) => <field.Input label={getTranslation(ui, "labels", "displayName")} />}
            </form.AppField>
          </fieldset>
        ) : null}
        <fieldset>
          <form.AppField name="email">
            {(field) => <field.Input label={getTranslation(ui, "labels", "emailAddress")} type="email" />}
          </form.AppField>
        </fieldset>
        <fieldset>
          <form.AppField name="password">
            {(field) => <field.Input label={getTranslation(ui, "labels", "password")} type="password" />}
          </form.AppField>
        </fieldset>
        <Policies />
        <fieldset>
          <form.SubmitButton>{getTranslation(ui, "labels", "createAccount")}</form.SubmitButton>
          <form.ErrorMessage />
        </fieldset>
        {onSignInClick ? (
          <form.Action onClick={onSignInClick}>
            {getTranslation(ui, "prompts", "haveAccount")} {getTranslation(ui, "labels", "signIn")}
          </form.Action>
        ) : null}
      </form.AppForm>
    </form>
  );
}

// packages/angular/src/lib/auth/forms/sign-up-auth-form.ts
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, output, effect, computed } from "@angular/core";
import { CommonModule } from "@angular/common";
import { injectForm, injectStore, TanStackAppField, TanStackField } from "@tanstack/angular-form";
import { FirebaseUIError, createUserWithEmailAndPassword, hasBehavior } from "@invertase/firebaseui-core";
import { UserCredential } from "@angular/fire/auth";

import { PoliciesComponent } from "../../components/policies";
import { injectSignUpAuthFormSchema, injectTranslation, injectUI } from "../../provider";
import {
  FormInputComponent,
  FormSubmitComponent,
  FormErrorMessageComponent,
  FormActionComponent,
} from "../../components/form";

@Component({
  selector: "fui-sign-up-auth-form",
  standalone: true,
  imports: [
    CommonModule,
    TanStackField,
    TanStackAppField,
    PoliciesComponent,
    FormInputComponent,
    FormSubmitComponent,
    FormErrorMessageComponent,
    FormActionComponent,
  ],
  template: `
    <form (submit)="handleSubmit($event)" class="fui-form">
      @if (requireDisplayNameField()) {
        <fieldset>
          <fui-form-input name="displayName" tanstack-app-field [tanstackField]="form" [label]="displayNameLabel()" />
        </fieldset>
      }
      <fieldset>
        <fui-form-input name="email" tanstack-app-field [tanstackField]="form" [label]="emailLabel()" type="email" />
      </fieldset>
      <fieldset>
        <fui-form-input
          name="password"
          tanstack-app-field
          [tanstackField]="form"
          [label]="passwordLabel()"
          type="password"
        />
      </fieldset>
      <fui-policies />
      <fieldset>
        <fui-form-submit [state]="state()">
          {{ createAccountLabel() }}
        </fui-form-submit>
        <fui-form-error-message [state]="state()" />
      </fieldset>

      @if (signIn) {
        <button fui-form-action (click)="signIn.emit()">{{ haveAccountLabel() }} {{ signInLabel() }}</button>
      }
    </form>
  `,
})
export class SignUpAuthFormComponent {
  private ui = injectUI();
  private formSchema = injectSignUpAuthFormSchema();

  requireDisplayNameField = computed(() => {
    return hasBehavior(this.ui(), "requireDisplayName");
  });

  emailLabel = injectTranslation("labels", "emailAddress");
  displayNameLabel = injectTranslation("labels", "displayName");
  passwordLabel = injectTranslation("labels", "password");
  createAccountLabel = injectTranslation("labels", "createAccount");
  haveAccountLabel = injectTranslation("prompts", "haveAccount");
  signInLabel = injectTranslation("labels", "signIn");
  unknownErrorLabel = injectTranslation("errors", "unknownError");

  signUp = output<UserCredential>();
  signIn = output<void>();

  form = injectForm({
    defaultValues: {
      email: "",
      password: "",
      displayName: this.requireDisplayNameField() ? "" : undefined,
    },
  });

  state = injectStore(this.form, (state) => state);

  handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    event.stopPropagation();
    this.form.handleSubmit();
  }

  constructor() {
    effect(() => {
      this.form.update({
        validators: {
          onBlur: this.formSchema(),
          onSubmitAsync: async ({ value }) => {
            try {
              const credential = await createUserWithEmailAndPassword(
                this.ui(),
                value.email,
                value.password,
                value.displayName
              );
              this.signUp.emit(credential);
              return;
            } catch (error) {
              if (error instanceof FirebaseUIError) {
                return error.message;
              }

              console.error(error);
              return this.unknownErrorLabel();
            }
          },
        },
      });
    });
  }
}
