// packages/shadcn/src/components/sign-in-auth-form.tsx
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

"use client";

import type { SignInAuthFormSchema } from "@firebase-oss/ui-core";
import {
  useSignInAuthFormAction,
  useSignInAuthFormSchema,
  useUI,
  type SignInAuthFormProps,
} from "@firebase-oss/ui-react";
import { useForm } from "react-hook-form";
import { standardSchemaResolver } from "@hookform/resolvers/standard-schema";
import { FirebaseUIError, getTranslation } from "@firebase-oss/ui-core";

import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Policies } from "./policies";

export type { SignInAuthFormProps };

export function SignInAuthForm(props: SignInAuthFormProps) {
  const ui = useUI();
  const schema = useSignInAuthFormSchema();
  const action = useSignInAuthFormAction();

  const form = useForm<SignInAuthFormSchema>({
    resolver: standardSchemaResolver(schema),
    mode: "onChange",
    defaultValues: {
      email: "",
      password: "",
    },
  });

  async function onSubmit(values: SignInAuthFormSchema) {
    try {
      const credential = await action(values);
      props.onSignIn?.(credential);
    } catch (error) {
      const message = error instanceof FirebaseUIError ? error.message : String(error);
      form.setError("root", { message });
    }
  }

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="flex flex-col gap-y-4">
        <FormField
          control={form.control}
          name="email"
          render={({ field }) => (
            <FormItem>
              <FormLabel>{getTranslation(ui, "labels", "emailAddress")}</FormLabel>
              <FormControl>
                <Input {...field} type="email" />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="password"
          render={({ field }) => (
            <FormItem>
              <FormLabel className="flex items-center gap-2">
                <span className="grow">{getTranslation(ui, "labels", "password")}</span>
                {props.onForgotPasswordClick ? (
                  <Button type="button" variant="link" onClick={props.onForgotPasswordClick} size="sm">
                    <span className="text-xs">{getTranslation(ui, "labels", "forgotPassword")}</span>
                  </Button>
                ) : null}
              </FormLabel>
              <FormControl>
                <Input {...field} type="password" />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        <Policies />
        <Button type="submit" disabled={ui.state !== "idle"}>
          {getTranslation(ui, "labels", "signIn")}
        </Button>
        {form.formState.errors.root && <FormMessage>{form.formState.errors.root.message}</FormMessage>}
        {props.onSignUpClick ? (
          <>
            <Button type="button" variant="link" size="sm" onClick={props.onSignUpClick}>
              <span className="text-xs">
                {getTranslation(ui, "prompts", "noAccount")} {getTranslation(ui, "labels", "signUp")}
              </span>
            </Button>
          </>
        ) : null}
      </form>
    </Form>
  );
}

// packages/angular/src/lib/auth/forms/sign-in-auth-form.ts
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, output, effect } from "@angular/core";
import { CommonModule } from "@angular/common";
import { UserCredential } from "@angular/fire/auth";
import { injectForm, TanStackField, TanStackAppField, injectStore } from "@tanstack/angular-form";
import { FirebaseUIError, signInWithEmailAndPassword } from "@firebase-ui/core";

import { injectSignInAuthFormSchema, injectTranslation, injectUI } from "../../provider";
import { PoliciesComponent } from "../../components/policies";
import {
  FormInputComponent,
  FormSubmitComponent,
  FormErrorMessageComponent,
  FormActionComponent,
} from "../../components/form";

@Component({
  selector: "fui-sign-in-auth-form",
  standalone: true,
  imports: [
    CommonModule,
    TanStackField,
    TanStackAppField,
    PoliciesComponent,
    FormInputComponent,
    FormSubmitComponent,
    FormErrorMessageComponent,
    FormActionComponent,
  ],
  template: `
    <form (submit)="handleSubmit($event)" class="fui-form">
      <fieldset>
        <fui-form-input
          name="email"
          tanstack-app-field
          [tanstackField]="form"
          label="{{ emailLabel() }}"
        ></fui-form-input>
      </fieldset>
      <fieldset>
        <fui-form-input name="password" tanstack-app-field [tanstackField]="form" label="{{ passwordLabel() }}">
          @if (forgotPassword) {
            <button fui-form-action (click)="forgotPassword.emit()">
              {{ forgotPasswordLabel() }}
            </button>
          }
        </fui-form-input>
      </fieldset>

      <fui-policies />

      <fieldset>
        <fui-form-submit [state]="state()">
          {{ signInLabel() }}
        </fui-form-submit>
        <fui-form-error-message [state]="state()" />
      </fieldset>

      @if (signUp) {
        <button fui-form-action (click)="signUp.emit()">{{ noAccountLabel() }} {{ registerLabel() }}</button>
      }
    </form>
  `,
})
export class SignInAuthFormComponent {
  private ui = injectUI();
  private formSchema = injectSignInAuthFormSchema();

  emailLabel = injectTranslation("labels", "emailAddress");
  passwordLabel = injectTranslation("labels", "password");
  forgotPasswordLabel = injectTranslation("labels", "forgotPassword");
  signInLabel = injectTranslation("labels", "signIn");
  noAccountLabel = injectTranslation("prompts", "noAccount");
  registerLabel = injectTranslation("labels", "register");
  unknownErrorLabel = injectTranslation("errors", "unknownError");

  forgotPassword = output<void>();
  signUp = output<void>();
  signIn = output<UserCredential>();

  form = injectForm({
    defaultValues: {
      email: "",
      password: "",
    },
  });

  state = injectStore(this.form, (state) => state);

  handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    event.stopPropagation();
    this.form.handleSubmit();
  }

  constructor() {
    effect(() => {
      this.form.update({
        validators: {
          onChange: this.formSchema(),
          onBlur: this.formSchema(),
          onSubmit: this.formSchema(),
          onSubmitAsync: async ({ value }) => {
            try {
              const credential = await signInWithEmailAndPassword(this.ui(), value.email, value.password);
              this.signIn?.emit(credential);
              return;
            } catch (error) {
              if (error instanceof FirebaseUIError) {
                return error.message;
              }

              return this.unknownErrorLabel();
            }
          },
        },
      });
    });
  }
}
