// packages/react/src/components/form.tsx
import { ComponentProps, PropsWithChildren } from "react";
import { AnyFieldApi, createFormHook, createFormHookContexts } from "@tanstack/react-form";
import { Button } from "./button";
import { cn } from "~/utils/cn";

const { fieldContext, useFieldContext, formContext, useFormContext } = createFormHookContexts();

function FieldMetadata({ className, ...props }: ComponentProps<"div"> & { field: AnyFieldApi }) {
  if (!props.field.state.meta.isTouched || !props.field.state.meta.errors.length) {
    return null;
  }
  
  return (
    <div>
      <div role="alert" aria-live="polite" className={cn("fui-form__error", className)} {...props}>
        {props.field.state.meta.errors.map((error) => error.message).join(", ")}
      </div>
    </div>
  );
}

function Input(props: PropsWithChildren<ComponentProps<"input"> & { label: string }>) {
  const field = useFieldContext<string>();

  return (
    <label htmlFor={field.name}>
      <span>{props.label}</span>
      <input
        aria-invalid={field.state.meta.isTouched && field.state.meta.errors.length > 0}
        id={field.name}
        name={field.name}
        value={field.state.value}
        onBlur={() => {
          field.handleBlur();
        }}
        onChange={(e) => {
          field.handleChange(e.target.value);
        }}
      />
      {props.children ? <>{props.children}</> : null}
      <FieldMetadata field={field} />
    </label>
  );
}

function Action({ className, ...props }: ComponentProps<"button">) {
  return <button type="button" {...props} className={cn("fui-form__action", className)} />;
}

function SubmitButton(props: ComponentProps<"button">) {
  const form = useFormContext();

  return (
    <form.Subscribe selector={(state) => state.isSubmitting}>
      {(isSubmitting) => <Button {...props} type="submit" disabled={isSubmitting} />}
    </form.Subscribe>
  );
}

function ErrorMessage() {
  const form = useFormContext();

  return (
    <form.Subscribe selector={(state) => [state.errorMap]}>
      {([errorMap]) => {
        if (errorMap.onSubmit) {
          return <div className="fui-form__error">{errorMap.onSubmit.toString()}</div>;
        }

        return null;
      }}
    </form.Subscribe>
  );
}

export const form = createFormHook({
  fieldComponents: {
    Input,
  },
  formComponents: {
    SubmitButton,
    ErrorMessage,
    Action,
  },
  fieldContext,
  formContext,
});

// packages/angular/src/lib/components/form/form.component.ts
import { Component, computed, input } from "@angular/core";
import { AnyFieldApi, AnyFormState, injectField } from "@tanstack/angular-form";
import { ButtonComponent } from "../button/button.component";

@Component({
  selector: "fui-form-metadata",
  standalone: true,
  template: `
    @if (field().state.meta.isTouched && errors().length > 0) {
      <div>
        <div role="alert" aria-live="polite" class="fui-form__error">
          {{ errors() }}
        </div>
      </div>
    }
  `,
})
export class FormMetadataComponent {
  field = input.required<AnyFieldApi>();
  errors = computed(() => this.field().state.meta.errors.map((error) => error.message).join(", "));
}

@Component({
  selector: "fui-form-input",
  standalone: true,
  imports: [FormMetadataComponent],
  template: `
    <label [for]="field.api.name">
      <span>{{ label() }}</span>
      <input
        [attr.aria-invalid]="field.api.state.meta.isTouched && field.api.state.meta.errors.length > 0"
        [id]="field.api.name"
        [name]="field.api.name"
        [value]="field.api.state.value"
        (blur)="field.api.handleBlur()"
        (input)="field.api.handleChange($any($event).target.value)"
      />
      <ng-content></ng-content>
      <fui-form-metadata [field]="field.api"></fui-form-metadata>
    </label>
  `,
})
export class FormInputComponent {
  field = injectField<string>();
  label = input.required<string>();
}

@Component({
  selector: "button[fui-form-action]",
  standalone: true,
  host: {
    class: "fui-form__action",
    type: "button",
  },
  template: `<ng-content></ng-content> `,
})
export class FormActionComponent {}

@Component({
  selector: "fui-form-submit",
  standalone: true,
  imports: [ButtonComponent],
  host: {
    type: "submit",
  },
  template: `
    <button fui-button class="fui-form__action" [class]="class()" [disabled]="isSubmitting()">
      <ng-content></ng-content>
    </button>
  `,
})
export class FormSubmitComponent {
  class = input<string>();
  state = input.required<AnyFormState>();

  isSubmitting = computed(() => this.state().isSubmitting);
}

@Component({
  selector: "fui-form-error-message",
  standalone: true,
  template: `
    @if (errorMessage()) {
      <div class="fui-form__error">
        {{ errorMessage() }}
      </div>
    }
  `,
})
export class FormErrorMessageComponent {
  state = input.required<AnyFormState>();

  errorMessage = computed(() => {
    return this.state().errorMap?.onSubmit ? String(this.state().errorMap.onSubmit) : undefined;
  });
}
