// examples/angular/src/app/screens/email-link-auth-screen-w-oauth.ts
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, inject } from "@angular/core";
import { CommonModule } from "@angular/common";
import { EmailLinkAuthScreenComponent, GoogleSignInButtonComponent } from "@invertase/firebaseui-angular";
import { Router } from "@angular/router";

@Component({
  selector: "app-email-link-auth-screen-w-oauth",
  standalone: true,
  imports: [CommonModule, EmailLinkAuthScreenComponent, GoogleSignInButtonComponent],
  template: `
    <fui-email-link-auth-screen (emailSent)="onEmailSent()" (signIn)="onSignIn()">
      <fui-google-sign-in-button></fui-google-sign-in-button>
    </fui-email-link-auth-screen>
  `,
  styles: [],
})
export class EmailLinkAuthScreenWithOAuthComponent {
  private router = inject(Router);

  onEmailSent() {
    alert("email sent - please check your email");
  }

  onSignIn() {
    this.router.navigate(["/"]);
  }
}

// examples/react/src/screens/email-link-auth-screen-w-oauth.tsx
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

"use client";

import {
  AppleSignInButton,
  EmailLinkAuthScreen,
  FacebookSignInButton,
  GitHubSignInButton,
  GoogleSignInButton,
  MicrosoftSignInButton,
  TwitterSignInButton,
} from "@invertase/firebaseui-react";
import { useNavigate } from "react-router";

export default function EmailLinkAuthScreenWithOAuthPage() {
  const navigate = useNavigate();

  return (
    <EmailLinkAuthScreen
      onEmailSent={() => {
        alert("Email has been sent - please check your email");
      }}
      onSignIn={() => {
        navigate("/");
      }}
    >
      <GoogleSignInButton />
      <FacebookSignInButton />
      <AppleSignInButton />
      <GitHubSignInButton />
      <MicrosoftSignInButton />
      <TwitterSignInButton />
    </EmailLinkAuthScreen>
  );
}
