// packages/react/src/auth/oauth/apple-sign-in-button.tsx
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

"use client";

import { getTranslation } from "@firebase-ui/core";
import { OAuthProvider } from "firebase/auth";
import { useUI } from "~/hooks";
import { OAuthButton } from "./oauth-button";
import AppleSvgLogo from "~/components/logos/apple/Logo";

export type AppleSignInButtonProps = {
  provider?: OAuthProvider;
  themed?: boolean;
};

export function AppleSignInButton({ provider, themed }: AppleSignInButtonProps) {
  const ui = useUI();

  return (
    <OAuthButton provider={provider || new OAuthProvider("apple.com")} themed={themed}>
      <AppleLogo />
      <span>{getTranslation(ui, "labels", "signInWithApple")}</span>
    </OAuthButton>
  );
}

export function AppleLogo() {
  return <AppleSvgLogo className="fui-provider__icon" />;
}

// packages/angular/src/lib/auth/oauth/apple-sign-in-button.ts
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, input } from "@angular/core";
import { CommonModule } from "@angular/common";
import { OAuthButtonComponent } from "./oauth-button";
import { injectTranslation, injectUI } from "../../provider";
import { OAuthProvider } from "@angular/fire/auth";
import { AppleLogoComponent } from "../../components/logos/apple";

@Component({
  selector: "fui-apple-sign-in-button",
  standalone: true,
  imports: [CommonModule, OAuthButtonComponent, AppleLogoComponent],
  template: `
    <fui-oauth-button [provider]="appleProvider">
      <fui-apple-logo />
      <span>{{ signInWithAppleLabel() }}</span>
    </fui-oauth-button>
  `,
})
export class AppleSignInButtonComponent {
  ui = injectUI();
  signInWithAppleLabel = injectTranslation("labels", "signInWithApple");

  private defaultProvider = new OAuthProvider("apple.com");

  provider = input<OAuthProvider>();

  get appleProvider() {
    return this.provider() || this.defaultProvider;
  }
}
