// packages/react/src/auth/oauth/yahoo-sign-in-button.tsx
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

"use client";

import { getTranslation } from "@firebase-oss/ui-core";
import { OAuthProvider, type UserCredential } from "firebase/auth";
import { useUI } from "~/hooks";
import { OAuthButton } from "./oauth-button";
import YahooSvgLogo from "~/components/logos/yahoo/Logo";
import { cn } from "~/utils/cn";

/** Props for the YahooSignInButton component. */
export type YahooSignInButtonProps = {
  /** Optional OAuth provider instance. Defaults to Yahoo provider. */
  provider?: OAuthProvider;
  /** Whether to apply themed styling. */
  themed?: boolean;
  /** Callback function called when sign-in is successful. */
  onSignIn?: (credential: UserCredential) => void;
};

/**
 * A button component for signing in with Yahoo.
 *
 * @returns The Yahoo sign-in button component.
 */
export function YahooSignInButton({ provider, ...props }: YahooSignInButtonProps) {
  const ui = useUI();

  return (
    <OAuthButton {...props} provider={provider || new OAuthProvider("yahoo.com")}>
      <YahooLogo />
      <span>{getTranslation(ui, "labels", "signInWithYahoo")}</span>
    </OAuthButton>
  );
}

/**
 * The Yahoo logo SVG component.
 *
 * @returns The Yahoo logo component.
 */
export function YahooLogo({ className, ...props }: React.SVGProps<SVGSVGElement>) {
  return <YahooSvgLogo className={cn("fui-provider__icon", className)} {...props} />;
}

// packages/angular/src/lib/auth/oauth/yahoo-sign-in-button.ts
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, input, output } from "@angular/core";
import { CommonModule } from "@angular/common";
import { OAuthButtonComponent } from "./oauth-button";
import { injectTranslation } from "../../provider";
import { OAuthProvider, UserCredential } from "@angular/fire/auth";
import { YahooLogoComponent } from "../../components/logos/yahoo";

@Component({
  selector: "fui-yahoo-sign-in-button",
  standalone: true,
  imports: [CommonModule, OAuthButtonComponent, YahooLogoComponent],
  host: {
    style: "display: block;",
  },
  template: `
    <fui-oauth-button [provider]="yahooProvider" [themed]="themed()" (signIn)="signIn.emit($event)">
      <fui-yahoo-logo />
      <span>{{ signInWithYahooLabel() }}</span>
    </fui-oauth-button>
  `,
})
/**
 * A button component for signing in with Yahoo.
 */
export class YahooSignInButtonComponent {
  signInWithYahooLabel = injectTranslation("labels", "signInWithYahoo");
  /** Whether to use themed styling. */
  themed = input<boolean>(false);
  /** Event emitter for successful sign-in. */
  signIn = output<UserCredential>();

  private defaultProvider = new OAuthProvider("yahoo.com");

  /** Optional custom OAuth provider configuration. */
  provider = input<OAuthProvider>();

  get yahooProvider() {
    return this.provider() || this.defaultProvider;
  }
}
