// packages/react/src/auth/forms/mfa/sms-multi-factor-assertion-form.tsx
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {
  PhoneAuthProvider,
  PhoneMultiFactorGenerator,
  type MultiFactorInfo,
  type RecaptchaVerifier,
  type UserCredential,
} from "firebase/auth";
import { useCallback, useRef, useState } from "react";

import {
  FirebaseUIError,
  getTranslation,
  signInWithMultiFactorAssertion,
  verifyPhoneNumber,
} from "@firebase-oss/ui-core";
import { form } from "~/components/form";

import { useMultiFactorPhoneAuthVerifyFormSchema, useRecaptchaVerifier, useUI } from "~/hooks";

type PhoneMultiFactorInfo = MultiFactorInfo & {
  phoneNumber?: string;
};

/**
 * Creates a memoized action function for verifying a phone number during SMS multi-factor assertion.
 *
 * @returns A callback function that verifies a phone number using the provided hint and reCAPTCHA verifier.
 */
export function useSmsMultiFactorAssertionPhoneFormAction() {
  const ui = useUI();

  return useCallback(
    async ({ hint, recaptchaVerifier }: { hint: MultiFactorInfo; recaptchaVerifier: RecaptchaVerifier }) => {
      return await verifyPhoneNumber(ui, "", recaptchaVerifier, undefined, hint);
    },
    [ui]
  );
}

/** Options for the SMS multi-factor assertion phone form hook. */
type UseSmsMultiFactorAssertionPhoneForm = {
  /** The multi-factor info hint containing phone number information. */
  hint: MultiFactorInfo;
  /** The reCAPTCHA verifier instance. */
  recaptchaVerifier: RecaptchaVerifier;
  /** Callback function called when phone verification is successful. */
  onSuccess: (verificationId: string) => void;
};

/**
 * Creates a form hook for SMS multi-factor assertion phone number verification.
 *
 * @param options - The phone form options.
 * @returns A form instance configured for phone number verification.
 */
export function useSmsMultiFactorAssertionPhoneForm({
  hint,
  recaptchaVerifier,
  onSuccess,
}: UseSmsMultiFactorAssertionPhoneForm) {
  const action = useSmsMultiFactorAssertionPhoneFormAction();

  return form.useAppForm({
    validators: {
      onSubmitAsync: async () => {
        try {
          const verificationId = await action({ hint, recaptchaVerifier });
          return onSuccess(verificationId);
        } catch (error) {
          return error instanceof FirebaseUIError ? error.message : String(error);
        }
      },
    },
  });
}

type SmsMultiFactorAssertionPhoneFormProps = {
  hint: MultiFactorInfo;
  onSubmit: (verificationId: string) => void;
};

function SmsMultiFactorAssertionPhoneForm(props: SmsMultiFactorAssertionPhoneFormProps) {
  const ui = useUI();
  const recaptchaContainerRef = useRef<HTMLDivElement>(null);
  const recaptchaVerifier = useRecaptchaVerifier(recaptchaContainerRef);
  const form = useSmsMultiFactorAssertionPhoneForm({
    hint: props.hint,
    recaptchaVerifier: recaptchaVerifier!,
    onSuccess: props.onSubmit,
  });

  return (
    <form
      className="fui-form"
      onSubmit={async (e) => {
        e.preventDefault();
        e.stopPropagation();
        await form.handleSubmit();
      }}
    >
      <form.AppForm>
        <fieldset>
          <label>
            <div data-input-description>
              {getTranslation(ui, "messages", "mfaSmsAssertionPrompt", {
                phoneNumber: (props.hint as PhoneMultiFactorInfo).phoneNumber || "",
              })}
            </div>
          </label>
        </fieldset>
        <fieldset>
          <div className="fui-recaptcha-container" ref={recaptchaContainerRef} />
        </fieldset>
        <fieldset>
          <form.SubmitButton>{getTranslation(ui, "labels", "sendCode")}</form.SubmitButton>
          <form.ErrorMessage />
        </fieldset>
      </form.AppForm>
    </form>
  );
}

/**
 * Creates a memoized action function for verifying the SMS verification code during multi-factor assertion.
 *
 * @returns A callback function that verifies the code and signs in with the multi-factor assertion.
 */
export function useSmsMultiFactorAssertionVerifyFormAction() {
  const ui = useUI();

  return useCallback(
    async ({ verificationId, verificationCode }: { verificationId: string; verificationCode: string }) => {
      const credential = PhoneAuthProvider.credential(verificationId, verificationCode);
      const assertion = PhoneMultiFactorGenerator.assertion(credential);
      return await signInWithMultiFactorAssertion(ui, assertion);
    },
    [ui]
  );
}

/** Options for the SMS multi-factor assertion verify form hook. */
type UseSmsMultiFactorAssertionVerifyForm = {
  /** The verification ID from the phone verification step. */
  verificationId: string;
  /** Callback function called when verification is successful. */
  onSuccess: (credential: UserCredential) => void;
};

/**
 * Creates a form hook for SMS multi-factor assertion verification code input.
 *
 * @param options - The verify form options.
 * @returns A form instance configured for verification code input.
 */
export function useSmsMultiFactorAssertionVerifyForm({
  verificationId,
  onSuccess,
}: UseSmsMultiFactorAssertionVerifyForm) {
  const action = useSmsMultiFactorAssertionVerifyFormAction();
  const schema = useMultiFactorPhoneAuthVerifyFormSchema();

  return form.useAppForm({
    defaultValues: {
      verificationId,
      verificationCode: "",
    },
    validators: {
      onBlur: schema,
      onSubmitAsync: async ({ value }) => {
        try {
          const credential = await action(value);
          return onSuccess(credential);
        } catch (error) {
          return error instanceof FirebaseUIError ? error.message : String(error);
        }
      },
    },
  });
}

type SmsMultiFactorAssertionVerifyFormProps = {
  verificationId: string;
  onSuccess: (credential: UserCredential) => void;
};

function SmsMultiFactorAssertionVerifyForm(props: SmsMultiFactorAssertionVerifyFormProps) {
  const ui = useUI();
  const form = useSmsMultiFactorAssertionVerifyForm({
    verificationId: props.verificationId,
    onSuccess: props.onSuccess,
  });

  return (
    <form
      className="fui-form"
      onSubmit={async (e) => {
        e.preventDefault();
        e.stopPropagation();
        await form.handleSubmit();
      }}
    >
      <form.AppForm>
        <fieldset>
          <form.AppField name="verificationCode">
            {(field) => (
              <field.Input
                label={getTranslation(ui, "labels", "verificationCode")}
                type="text"
                description={getTranslation(ui, "prompts", "smsVerificationPrompt")}
              />
            )}
          </form.AppField>
        </fieldset>
        <fieldset>
          <form.SubmitButton>{getTranslation(ui, "labels", "verifyCode")}</form.SubmitButton>
          <form.ErrorMessage />
        </fieldset>
      </form.AppForm>
    </form>
  );
}

/** Props for the SmsMultiFactorAssertionForm component. */
export type SmsMultiFactorAssertionFormProps = {
  /** The multi-factor info hint containing phone number information. */
  hint: MultiFactorInfo;
  /** Optional callback function called when multi-factor assertion is successful. */
  onSuccess?: (credential: UserCredential) => void;
};

/**
 * A form component for SMS multi-factor authentication assertion.
 *
 * Handles the two-step process: first verifying the phone number, then verifying the SMS code.
 *
 * @returns The SMS multi-factor assertion form component.
 */
export function SmsMultiFactorAssertionForm(props: SmsMultiFactorAssertionFormProps) {
  const [verification, setVerification] = useState<{
    verificationId: string;
  } | null>(null);

  if (!verification) {
    return (
      <SmsMultiFactorAssertionPhoneForm
        hint={props.hint}
        onSubmit={(verificationId) => setVerification({ verificationId })}
      />
    );
  }

  return (
    <SmsMultiFactorAssertionVerifyForm
      verificationId={verification.verificationId}
      onSuccess={(credential) => {
        props.onSuccess?.(credential);
      }}
    />
  );
}

// packages/angular/src/lib/auth/forms/mfa/sms-multi-factor-assertion-form.ts
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { CommonModule } from "@angular/common";
import { Component, ElementRef, EventEmitter, Output, computed, effect, input, signal, viewChild } from "@angular/core";
import {
  FirebaseUIError,
  getTranslation,
  signInWithMultiFactorAssertion,
  verifyPhoneNumber,
} from "@firebase-oss/ui-core";
import { TanStackAppField, TanStackField, injectForm, injectStore } from "@tanstack/angular-form";
import { PhoneAuthProvider, PhoneMultiFactorGenerator, type MultiFactorInfo, type UserCredential } from "firebase/auth";
import { FormErrorMessageComponent, FormInputComponent, FormSubmitComponent } from "../../../components/form";
import {
  injectMultiFactorPhoneAuthVerifyFormSchema,
  injectRecaptchaVerifier,
  injectTranslation,
  injectUI,
} from "../../../provider";

type PhoneMultiFactorInfo = MultiFactorInfo & {
  phoneNumber?: string;
};

@Component({
  selector: "fui-sms-multi-factor-assertion-phone-form",
  standalone: true,
  imports: [CommonModule, FormSubmitComponent, FormErrorMessageComponent],
  host: {
    style: "display: block;",
  },
  template: `
    <form (submit)="handleSubmit($event)" class="fui-form">
      <fieldset>
        <label>
          <div data-input-description>
            {{ mfaSmsAssertionPrompt() }}
          </div>
        </label>
      </fieldset>
      <fieldset>
        <div class="fui-recaptcha-container" #recaptchaContainer></div>
      </fieldset>
      <fieldset>
        <fui-form-submit [state]="state()">
          {{ sendCodeLabel() }}
        </fui-form-submit>
        <fui-form-error-message [state]="state()" />
      </fieldset>
    </form>
  `,
})
/**
 * A form component for requesting SMS verification code during MFA assertion.
 */
export class SmsMultiFactorAssertionPhoneFormComponent {
  private ui = injectUI();

  /** The multi-factor info hint containing phone number details. */
  hint = input.required<MultiFactorInfo>();
  /** Event emitter fired when verification ID is received. */
  @Output() onSubmit = new EventEmitter<string>();

  sendCodeLabel = injectTranslation("labels", "sendCode");

  recaptchaContainer = viewChild.required<ElementRef<HTMLDivElement>>("recaptchaContainer");

  phoneNumber = computed(() => {
    const hint = this.hint() as PhoneMultiFactorInfo;
    return hint.phoneNumber || "";
  });

  mfaSmsAssertionPrompt = computed(() => {
    return getTranslation(this.ui(), "messages", "mfaSmsAssertionPrompt", { phoneNumber: this.phoneNumber() });
  });

  recaptchaVerifier = injectRecaptchaVerifier(() => this.recaptchaContainer());

  form = injectForm({
    defaultValues: {},
  });

  state = injectStore(this.form, (state) => state);

  constructor() {
    effect(() => {
      this.form.update({
        validators: {
          onSubmitAsync: async () => {
            try {
              const verifier = this.recaptchaVerifier();
              if (!verifier) {
                return "Recaptcha verifier not available";
              }

              const verificationId = await verifyPhoneNumber(this.ui(), "", verifier, undefined, this.hint());
              this.onSubmit.emit(verificationId);
              return;
            } catch (error) {
              return error instanceof FirebaseUIError ? error.message : String(error);
            }
          },
        },
      });
    });

    effect((onCleanup) => {
      const verifier = this.recaptchaVerifier();
      onCleanup(() => {
        if (verifier) {
          verifier.clear();
        }
      });
    });
  }

  async handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    event.stopPropagation();
    this.form.handleSubmit();
  }
}

@Component({
  selector: "fui-sms-multi-factor-assertion-verify-form",
  standalone: true,
  host: {
    style: "display: block;",
  },
  imports: [
    CommonModule,
    TanStackField,
    TanStackAppField,
    FormInputComponent,
    FormSubmitComponent,
    FormErrorMessageComponent,
  ],
  template: `
    <form (submit)="handleSubmit($event)" class="fui-form">
      <fieldset>
        <fui-form-input
          name="verificationCode"
          tanstack-app-field
          [tanstackField]="form"
          [label]="verificationCodeLabel()"
          [description]="smsVerificationPrompt()"
          type="text"
        ></fui-form-input>
      </fieldset>
      <fieldset>
        <fui-form-submit [state]="state()">
          {{ verifyCodeLabel() }}
        </fui-form-submit>
        <fui-form-error-message [state]="state()" />
      </fieldset>
    </form>
  `,
})
/**
 * A form component for verifying SMS code during MFA assertion.
 */
export class SmsMultiFactorAssertionVerifyFormComponent {
  private ui = injectUI();
  private formSchema = injectMultiFactorPhoneAuthVerifyFormSchema();

  /** The verification ID received from the phone form. */
  verificationId = input.required<string>();
  /** Event emitter for successful MFA assertion. */
  @Output() onSuccess = new EventEmitter<UserCredential>();

  verificationCodeLabel = injectTranslation("labels", "verificationCode");
  verifyCodeLabel = injectTranslation("labels", "verifyCode");
  smsVerificationPrompt = injectTranslation("prompts", "smsVerificationPrompt");
  unknownErrorLabel = injectTranslation("errors", "unknownError");

  form = injectForm({
    defaultValues: {
      verificationId: "",
      verificationCode: "",
    },
  });

  state = injectStore(this.form, (state) => state);

  constructor() {
    effect(() => {
      this.form.setFieldValue("verificationId", this.verificationId());
    });

    effect(() => {
      this.form.update({
        validators: {
          onBlur: this.formSchema(),
          onSubmit: this.formSchema(),
          onSubmitAsync: async ({ value }) => {
            try {
              const credential = PhoneAuthProvider.credential(value.verificationId, value.verificationCode);
              const assertion = PhoneMultiFactorGenerator.assertion(credential);
              const result = await signInWithMultiFactorAssertion(this.ui(), assertion);
              this.onSuccess.emit(result);
              return;
            } catch (error) {
              return error instanceof FirebaseUIError ? error.message : String(error);
            }
          },
        },
      });
    });
  }

  async handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    event.stopPropagation();
    this.form.handleSubmit();
  }
}

@Component({
  selector: "fui-sms-multi-factor-assertion-form",
  standalone: true,
  imports: [CommonModule, SmsMultiFactorAssertionPhoneFormComponent, SmsMultiFactorAssertionVerifyFormComponent],
  host: {
    style: "display: block;",
  },
  template: `
    <div class="fui-content">
      @if (verification()) {
        <fui-sms-multi-factor-assertion-verify-form
          [verificationId]="verification()!.verificationId"
          (onSuccess)="onSuccess.emit($event)"
        />
      } @else {
        <fui-sms-multi-factor-assertion-phone-form [hint]="hint()" (onSubmit)="handlePhoneSubmit($event)" />
      }
    </div>
  `,
})
/**
 * A form component for SMS multi-factor authentication assertion.
 *
 * Manages the flow between requesting and verifying SMS codes for MFA.
 */
export class SmsMultiFactorAssertionFormComponent {
  /** The multi-factor info hint containing phone number details. */
  hint = input.required<MultiFactorInfo>();
  /** Event emitter for successful MFA assertion. */
  @Output() onSuccess = new EventEmitter<UserCredential>();

  verification = signal<{ verificationId: string } | null>(null);

  handlePhoneSubmit(verificationId: string) {
    this.verification.set({ verificationId });
  }
}
