// examples/angular/src/app/screens/sign-in-auth-screen-w-oauth/sign-in-auth-screen-w-oauth.component.ts
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component } from "@angular/core";
import { CommonModule } from "@angular/common";
import { SignInAuthScreenComponent, GoogleSignInButtonComponent } from "@invertase/firebaseui-angular";

@Component({
  selector: "app-sign-in-auth-screen-w-oauth",
  standalone: true,
  imports: [CommonModule, SignInAuthScreenComponent, GoogleSignInButtonComponent],
  template: `
    <fui-sign-in-auth-screen>
      <fui-google-sign-in-button></fui-google-sign-in-button>
    </fui-sign-in-auth-screen>
  `,
  styles: [],
})
export class SignInAuthScreenWithOAuthComponent {}

// examples/nextjs/app/screens/sign-in-auth-screen-w-oauth/page.tsx
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

"use client";

import { GoogleSignInButton, SignInAuthScreen } from "@invertase/firebaseui-react";
import { useRouter } from "next/navigation";

export default function SignInAuthScreenWithOAuthPage() {
  const router = useRouter();

  return (
    <SignInAuthScreen
      onForgotPasswordClick={() => router.push("/password-reset-screen")}
      onRegisterClick={() => router.push("/sign-up-auth-screen")}
    >
      <GoogleSignInButton />
    </SignInAuthScreen>
  );
}
