// packages/angular/src/lib/auth/oauth/oauth-button.component.ts
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, input, signal } from "@angular/core";
import { CommonModule } from "@angular/common";
import { ButtonComponent } from "../../components/button/button.component";
import { injectTranslation, injectUI } from "../../provider";
import { AuthProvider } from "@angular/fire/auth";
import { FirebaseUIError, signInWithProvider } from "@firebase-ui/core";

@Component({
  selector: "fui-oauth-button",
  standalone: true,
  imports: [CommonModule, ButtonComponent],
  template: `
    <div>
      <button
        fui-button
        type="button"
        (click)="handleOAuthSignIn()"
        [disabled]="ui().state !== 'idle'"
        [attr.data-provider]="provider().providerId"
        class="fui-provider__button"
      >
        <ng-content></ng-content>
      </button>

      @if (error()) {
        <div class="fui-form__error">{{ error() }}</div>
      }
    </div>
  `,
})
export class OAuthButtonComponent {
  ui = injectUI();
  unknownErrorLabel = injectTranslation("errors", "unknownError");
  provider = input.required<AuthProvider>();
  error = signal<string | undefined>(undefined);

  async handleOAuthSignIn() {
    this.error.set(undefined);
    try {
      await signInWithProvider(this.ui(), this.provider());
    } catch (error) {
      if (error instanceof FirebaseUIError) {
        this.error.set(error.message);
        return;
      }

      console.error(error);
      this.error.set(this.unknownErrorLabel());
    }
  }
}

// packages/react/src/auth/oauth/oauth-button.tsx
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

"use client";

import { FirebaseUIError, getTranslation, signInWithProvider } from "@firebase-ui/core";
import type { AuthProvider } from "firebase/auth";
import type { PropsWithChildren } from "react";
import { useState } from "react";
import { Button } from "~/components/button";
import { useUI } from "~/hooks";

export type OAuthButtonProps = PropsWithChildren<{
  provider: AuthProvider;
  themed?: boolean | string;
}>;

export function OAuthButton({ provider, children, themed }: OAuthButtonProps) {
  const ui = useUI();

  const [error, setError] = useState<string | null>(null);

  const handleOAuthSignIn = async () => {
    setError(null);
    try {
      await signInWithProvider(ui, provider);
    } catch (error) {
      if (error instanceof FirebaseUIError) {
        setError(error.message);
        return;
      }
      console.error(error);
      setError(getTranslation(ui, "errors", "unknownError"));
    }
  };

  return (
    <div>
      <Button
        type="button"
        data-themed={themed}
        data-provider={provider.providerId}
        disabled={ui.state !== "idle"}
        onClick={handleOAuthSignIn}
        className="fui-provider__button"
      >
        {children}
      </Button>
      {error && <div className="fui-form__error">{error}</div>}
    </div>
  );
}
