// packages/react/src/auth/forms/sign-in-auth-form.tsx
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

"use client";

import { FirebaseUIError, getTranslation, signInWithEmailAndPassword } from "@firebase-ui/core";
import type { UserCredential } from "firebase/auth";
import { useSignInAuthFormSchema, useUI } from "~/hooks";
import { form } from "~/components/form";
import { Policies } from "~/components/policies";
import { useCallback } from "react";

export type SignInAuthFormProps = {
  onSignIn?: (credential: UserCredential) => void;
  onForgotPasswordClick?: () => void;
  onSignUpClick?: () => void;
};

export function useSignInAuthFormAction() {
  const ui = useUI();

  return useCallback(
    async ({ email, password }: { email: string; password: string }) => {
      try {
        return await signInWithEmailAndPassword(ui, email, password);
      } catch (error) {
        if (error instanceof FirebaseUIError) {
          throw new Error(error.message);
        }

        console.error(error);
        throw new Error(getTranslation(ui, "errors", "unknownError"));
      }
    },
    [ui]
  );
}

export function useSignInAuthForm(onSuccess?: SignInAuthFormProps["onSignIn"]) {
  const schema = useSignInAuthFormSchema();
  const action = useSignInAuthFormAction();

  return form.useAppForm({
    defaultValues: {
      email: "",
      password: "",
    },
    validators: {
      onBlur: schema,
      onSubmit: schema,
      onSubmitAsync: async ({ value }) => {
        try {
          const credential = await action(value);
          return onSuccess?.(credential);
        } catch (error) {
          return error instanceof Error ? error.message : String(error);
        }
      },
    },
  });
}

export function SignInAuthForm({ onSignIn, onForgotPasswordClick, onSignUpClick }: SignInAuthFormProps) {
  const ui = useUI();
  const form = useSignInAuthForm(onSignIn);

  return (
    <form
      className="fui-form"
      onSubmit={async (e) => {
        e.preventDefault();
        e.stopPropagation();
        await form.handleSubmit();
      }}
    >
      <form.AppForm>
        <fieldset>
          <form.AppField name="email">
            {(field) => <field.Input label={getTranslation(ui, "labels", "emailAddress")} type="email" />}
          </form.AppField>
        </fieldset>
        <fieldset>
          <form.AppField name="password">
            {(field) => (
              <field.Input label={getTranslation(ui, "labels", "password")} type="password">
                {onForgotPasswordClick ? (
                  <form.Action onClick={onForgotPasswordClick}>
                    {getTranslation(ui, "labels", "forgotPassword")}
                  </form.Action>
                ) : null}
              </field.Input>
            )}
          </form.AppField>
        </fieldset>
        <Policies />
        <fieldset>
          <form.SubmitButton>{getTranslation(ui, "labels", "signIn")}</form.SubmitButton>
          <form.ErrorMessage />
        </fieldset>
        {onSignUpClick ? (
          <form.Action onClick={onSignUpClick}>
            {getTranslation(ui, "prompts", "noAccount")} {getTranslation(ui, "labels", "signUp")}
          </form.Action>
        ) : null}
      </form.AppForm>
    </form>
  );
}

// packages/angular/src/lib/auth/forms/sign-in-auth-form/sign-in-auth-form.component.ts
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, output, effect } from "@angular/core";
import { CommonModule } from "@angular/common";
import { UserCredential } from "@angular/fire/auth";
import { injectForm, TanStackField, TanStackAppField, injectStore } from "@tanstack/angular-form";
import { FirebaseUIError, signInWithEmailAndPassword } from "@firebase-ui/core";

import { injectSignInAuthFormSchema, injectTranslation, injectUI } from "../../../provider";
import { PoliciesComponent } from "../../../components/policies/policies.component";
import {
  FormInputComponent,
  FormSubmitComponent,
  FormErrorMessageComponent,
  FormActionComponent,
} from "../../../components/form/form.component";

@Component({
  selector: "fui-sign-in-auth-form",
  standalone: true,
  imports: [
    CommonModule,
    TanStackField,
    TanStackAppField,
    PoliciesComponent,
    FormInputComponent,
    FormSubmitComponent,
    FormErrorMessageComponent,
    FormActionComponent,
  ],
  template: `
    <form (submit)="handleSubmit($event)" class="fui-form">
      <fieldset>
        <fui-form-input
          name="email"
          tanstack-app-field
          [tanstackField]="form"
          label="{{ emailLabel() }}"
        ></fui-form-input>
      </fieldset>
      <fieldset>
        <fui-form-input name="password" tanstack-app-field [tanstackField]="form" label="{{ passwordLabel() }}">
          @if (forgotPassword) {
            <button fui-form-action (click)="forgotPassword.emit()">
              {{ forgotPasswordLabel() }}
            </button>
          }
        </fui-form-input>
      </fieldset>

      <fui-policies />

      <fieldset>
        <fui-form-submit [state]="state()">
          {{ signInLabel() }}
        </fui-form-submit>
        <fui-form-error-message [state]="state()" />
      </fieldset>

      @if (signUp) {
        <button fui-form-action (click)="signUp.emit()">{{ noAccountLabel() }} {{ registerLabel() }}</button>
      }
    </form>
  `,
})
export class SignInAuthFormComponent {
  private ui = injectUI();
  private formSchema = injectSignInAuthFormSchema();

  emailLabel = injectTranslation("labels", "emailAddress");
  passwordLabel = injectTranslation("labels", "password");
  forgotPasswordLabel = injectTranslation("labels", "forgotPassword");
  signInLabel = injectTranslation("labels", "signIn");
  noAccountLabel = injectTranslation("prompts", "noAccount");
  registerLabel = injectTranslation("labels", "register");
  unknownErrorLabel = injectTranslation("errors", "unknownError");

  forgotPassword = output<void>();
  signUp = output<void>();
  signIn = output<UserCredential>();

  form = injectForm({
    defaultValues: {
      email: "",
      password: "",
    },
  });

  state = injectStore(this.form, (state) => state);

  handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    event.stopPropagation();
    this.form.handleSubmit();
  }

  constructor() {
    effect(() => {
      this.form.update({
        validators: {
          onChange: this.formSchema(),
          onBlur: this.formSchema(),
          onSubmit: this.formSchema(),
          onSubmitAsync: async ({ value }) => {
            try {
              const credential = await signInWithEmailAndPassword(this.ui(), value.email, value.password);
              this.signIn?.emit(credential);
              return;
            } catch (error) {
              if (error instanceof FirebaseUIError) {
                return error.message;
              }

              return this.unknownErrorLabel();
            }
          },
        },
      });
    });
  }
}
