// packages/angular/src/lib/auth/forms/mfa/totp-multi-factor-enrollment-form.ts
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, signal, effect, output, computed, input } from "@angular/core";
import { CommonModule } from "@angular/common";
import { TanStackField, TanStackAppField, injectForm, injectStore } from "@tanstack/angular-form";
import { TotpMultiFactorGenerator, type TotpSecret } from "firebase/auth";
import {
  enrollWithMultiFactorAssertion,
  generateTotpSecret,
  generateTotpQrCode,
  FirebaseUIError,
} from "@firebase-oss/ui-core";
import { FormInputComponent, FormSubmitComponent, FormErrorMessageComponent } from "../../../components/form";
import { PoliciesComponent } from "../../../components/policies";
import {
  injectUI,
  injectTranslation,
  injectMultiFactorTotpAuthNumberFormSchema,
  injectMultiFactorTotpAuthVerifyFormSchema,
} from "../../../provider";

@Component({
  selector: "fui-totp-multi-factor-secret-generation-form",
  standalone: true,
  imports: [
    CommonModule,
    TanStackField,
    TanStackAppField,
    FormInputComponent,
    FormSubmitComponent,
    FormErrorMessageComponent,
    PoliciesComponent,
  ],
  template: `
    <form (submit)="handleSubmit($event)" class="fui-form">
      <fieldset>
        <fui-form-input
          name="displayName"
          tanstack-app-field
          [tanstackField]="form"
          label="{{ displayNameLabel() }}"
        ></fui-form-input>
      </fieldset>
      <fui-policies />
      <fieldset>
        <fui-form-submit [state]="state()">
          {{ generateQrCodeLabel() }}
        </fui-form-submit>
        <fui-form-error-message [state]="state()" />
      </fieldset>
    </form>
  `,
})
export class TotpMultiFactorSecretGenerationFormComponent {
  private ui = injectUI();
  private formSchema = injectMultiFactorTotpAuthNumberFormSchema();

  onSubmit = output<{ secret: TotpSecret; displayName: string }>();

  displayNameLabel = injectTranslation("labels", "displayName");
  generateQrCodeLabel = injectTranslation("labels", "generateQrCode");
  unknownErrorLabel = injectTranslation("errors", "unknownError");

  form = injectForm({
    defaultValues: {
      displayName: "",
    },
  });

  state = injectStore(this.form, (state) => state);

  constructor() {
    effect(() => {
      this.form.update({
        validators: {
          onBlur: this.formSchema(),
          onSubmit: this.formSchema(),
          onSubmitAsync: async ({ value }) => {
            try {
              if (!this.ui().auth.currentUser) {
                throw new Error("User must be authenticated to enroll with multi-factor authentication");
              }

              const secret = await generateTotpSecret(this.ui());
              this.onSubmit.emit({ secret, displayName: value.displayName });
              return;
            } catch (error) {
              if (error instanceof FirebaseUIError) {
                return error.message;
              }

              console.error(error);
              return this.unknownErrorLabel();
            }
          },
        },
      });
    });
  }

  async handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    event.stopPropagation();
    this.form.handleSubmit();
  }
}

@Component({
  selector: "fui-totp-multi-factor-verification-form",
  standalone: true,
  imports: [
    CommonModule,
    TanStackField,
    TanStackAppField,
    FormInputComponent,
    FormSubmitComponent,
    FormErrorMessageComponent,
    PoliciesComponent,
  ],
  template: `
    <div class="fui-qr-code-container">
      <img [src]="qrCodeDataUrl()" alt="TOTP QR Code" />
      <p>TODO: Scan this QR code with your authenticator app</p>
    </div>
    <form (submit)="handleSubmit($event)" class="fui-form">
      <fieldset>
        <fui-form-input
          name="verificationCode"
          tanstack-app-field
          [tanstackField]="form"
          label="{{ verificationCodeLabel() }}"
        ></fui-form-input>
      </fieldset>
      <fui-policies />
      <fieldset>
        <fui-form-submit [state]="state()">
          {{ verifyCodeLabel() }}
        </fui-form-submit>
        <fui-form-error-message [state]="state()" />
      </fieldset>
    </form>
  `,
})
export class TotpMultiFactorVerificationFormComponent {
  private ui = injectUI();
  private formSchema = injectMultiFactorTotpAuthVerifyFormSchema();

  secret = input.required<TotpSecret>();
  displayName = input.required<string>();
  onEnrollment = output<void>();

  verificationCodeLabel = injectTranslation("labels", "verificationCode");
  verifyCodeLabel = injectTranslation("labels", "verifyCode");
  unknownErrorLabel = injectTranslation("errors", "unknownError");

  form = injectForm({
    defaultValues: {
      verificationCode: "",
    },
  });

  state = injectStore(this.form, (state) => state);

  qrCodeDataUrl = computed(() => {
    return generateTotpQrCode(this.ui(), this.secret(), this.displayName());
  });

  constructor() {
    effect(() => {
      this.form.update({
        validators: {
          onBlur: this.formSchema(),
          onSubmit: this.formSchema(),
          onSubmitAsync: async ({ value }) => {
            try {
              const assertion = TotpMultiFactorGenerator.assertionForEnrollment(this.secret(), value.verificationCode);
              await enrollWithMultiFactorAssertion(this.ui(), assertion, this.displayName());
              this.onEnrollment.emit();
              return;
            } catch (error) {
              if (error instanceof FirebaseUIError) {
                return error.message;
              }
              if (error instanceof Error) {
                return error.message;
              }
              return this.unknownErrorLabel();
            }
          },
        },
      });
    });
  }

  async handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    event.stopPropagation();
    this.form.handleSubmit();
  }
}

@Component({
  selector: "fui-totp-multi-factor-enrollment-form",
  standalone: true,
  imports: [CommonModule, TotpMultiFactorSecretGenerationFormComponent, TotpMultiFactorVerificationFormComponent],
  template: `
    <div class="fui-form-container">
      @if (!enrollment()) {
        <fui-totp-multi-factor-secret-generation-form (onSubmit)="handleSecretGeneration($event)" />
      } @else {
        <fui-totp-multi-factor-verification-form
          [secret]="enrollment()!.secret"
          [displayName]="enrollment()!.displayName"
          (onEnrollment)="onEnrollment.emit()"
        />
      }
    </div>
  `,
})
export class TotpMultiFactorEnrollmentFormComponent {
  enrollment = signal<{ secret: TotpSecret; displayName: string } | null>(null);
  onEnrollment = output<void>();

  handleSecretGeneration(data: { secret: TotpSecret; displayName: string }) {
    this.enrollment.set(data);
  }
}

// packages/shadcn/src/registry/totp-multi-factor-enrollment-form.tsx
"use client";

import { useState } from "react";
import { TotpMultiFactorGenerator, type TotpSecret } from "firebase/auth";
import {
  enrollWithMultiFactorAssertion,
  FirebaseUIError,
  generateTotpQrCode,
  generateTotpSecret,
  getTranslation,
} from "@firebase-oss/ui-core";
import {
  useMultiFactorTotpAuthNumberFormSchema,
  useMultiFactorTotpAuthVerifyFormSchema,
  useUI,
} from "@firebase-oss/ui-react";
import { useForm } from "react-hook-form";
import { standardSchemaResolver } from "@hookform/resolvers/standard-schema";

import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { InputOTP, InputOTPGroup, InputOTPSlot } from "@/components/ui/input-otp";

type TotpMultiFactorSecretGenerationFormProps = {
  onSubmit: (secret: TotpSecret, displayName: string) => void;
};

function TotpMultiFactorSecretGenerationForm(props: TotpMultiFactorSecretGenerationFormProps) {
  const ui = useUI();
  const schema = useMultiFactorTotpAuthNumberFormSchema();

  const form = useForm<{ displayName: string }>({
    resolver: standardSchemaResolver(schema),
    defaultValues: {
      displayName: "",
    },
  });

  const onSubmit = async (values: { displayName: string }) => {
    try {
      const secret = await generateTotpSecret(ui);
      props.onSubmit(secret, values.displayName);
    } catch (error) {
      const message = error instanceof FirebaseUIError ? error.message : String(error);
      form.setError("root", { message });
    }
  };

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
        <FormField
          control={form.control}
          name="displayName"
          render={({ field }) => (
            <FormItem>
              <FormLabel>{getTranslation(ui, "labels", "displayName")}</FormLabel>
              <FormControl>
                <Input {...field} type="text" />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        <Button type="submit" disabled={ui.state !== "idle"}>
          {getTranslation(ui, "labels", "generateQrCode")}
        </Button>
        {form.formState.errors.root && <FormMessage>{form.formState.errors.root.message}</FormMessage>}
      </form>
    </Form>
  );
}

type MultiFactorEnrollmentVerifyTotpFormProps = {
  secret: TotpSecret;
  displayName: string;
  onSuccess: () => void;
};

export function MultiFactorEnrollmentVerifyTotpForm(props: MultiFactorEnrollmentVerifyTotpFormProps) {
  const ui = useUI();
  const schema = useMultiFactorTotpAuthVerifyFormSchema();

  const form = useForm<{ verificationCode: string }>({
    resolver: standardSchemaResolver(schema),
    defaultValues: {
      verificationCode: "",
    },
  });

  const onSubmit = async (values: { verificationCode: string }) => {
    try {
      const assertion = TotpMultiFactorGenerator.assertionForEnrollment(props.secret, values.verificationCode);
      await enrollWithMultiFactorAssertion(ui, assertion, values.verificationCode);
      props.onSuccess();
    } catch (error) {
      const message = error instanceof FirebaseUIError ? error.message : String(error);
      form.setError("root", { message });
    }
  };

  const qrCodeDataUrl = generateTotpQrCode(ui, props.secret, props.displayName);

  return (
    <div className="space-y-4">
      <div className="flex justify-center">
        <div className="border rounded-lg p-4">
          <img src={qrCodeDataUrl} alt="TOTP QR Code" className="mx-auto" />
          <p className="text-sm text-muted-foreground text-center mt-2">
            Scan this QR code with your authenticator app
          </p>
        </div>
      </div>
      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
          <FormField
            control={form.control}
            name="verificationCode"
            render={({ field }) => (
              <FormItem>
                <FormLabel>{getTranslation(ui, "labels", "verificationCode")}</FormLabel>
                <FormControl>
                  <InputOTP maxLength={6} {...field}>
                    <InputOTPGroup>
                      <InputOTPSlot index={0} />
                      <InputOTPSlot index={1} />
                      <InputOTPSlot index={2} />
                      <InputOTPSlot index={3} />
                      <InputOTPSlot index={4} />
                      <InputOTPSlot index={5} />
                    </InputOTPGroup>
                  </InputOTP>
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
          <Button type="submit" disabled={ui.state !== "idle"}>
            {getTranslation(ui, "labels", "verifyCode")}
          </Button>
          {form.formState.errors.root && <FormMessage>{form.formState.errors.root.message}</FormMessage>}
        </form>
      </Form>
    </div>
  );
}

export type TotpMultiFactorEnrollmentFormProps = {
  onSuccess?: () => void;
};

export function TotpMultiFactorEnrollmentForm(props: TotpMultiFactorEnrollmentFormProps) {
  const ui = useUI();

  const [enrollment, setEnrollment] = useState<{
    secret: TotpSecret;
    displayName: string;
  } | null>(null);

  if (!ui.auth.currentUser) {
    throw new Error("User must be authenticated to enroll with multi-factor authentication");
  }

  if (!enrollment) {
    return (
      <TotpMultiFactorSecretGenerationForm onSubmit={(secret, displayName) => setEnrollment({ secret, displayName })} />
    );
  }

  return (
    <MultiFactorEnrollmentVerifyTotpForm
      {...enrollment}
      onSuccess={() => {
        props.onSuccess?.();
      }}
    />
  );
}
