// packages/angular/src/lib/components/legacy-sign-in-recovery.ts
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { CommonModule } from "@angular/common";
import { Component, HostListener } from "@angular/core";
import { ButtonComponent } from "./button";
import { injectClearLegacySignInRecovery, injectLegacySignInRecovery, injectTranslation } from "../provider";
import { AppleSignInButtonComponent } from "../auth/oauth/apple-sign-in-button";
import { FacebookSignInButtonComponent } from "../auth/oauth/facebook-sign-in-button";
import { GitHubSignInButtonComponent } from "../auth/oauth/github-sign-in-button";
import { GoogleSignInButtonComponent } from "../auth/oauth/google-sign-in-button";
import { MicrosoftSignInButtonComponent } from "../auth/oauth/microsoft-sign-in-button";
import { TwitterSignInButtonComponent } from "../auth/oauth/twitter-sign-in-button";
import { YahooSignInButtonComponent } from "../auth/oauth/yahoo-sign-in-button";

@Component({
  selector: "fui-legacy-sign-in-recovery",
  standalone: true,
  imports: [
    CommonModule,
    ButtonComponent,
    AppleSignInButtonComponent,
    FacebookSignInButtonComponent,
    GitHubSignInButtonComponent,
    GoogleSignInButtonComponent,
    MicrosoftSignInButtonComponent,
    TwitterSignInButtonComponent,
    YahooSignInButtonComponent,
  ],
  host: {
    style: "display: block;",
  },
  template: `
    @if (recovery()) {
      <div class="fui-legacy-sign-in-recovery-modal" (click)="handleBackdropClick($event)">
        <div
          [attr.aria-label]="selectMethodLabel()"
          aria-modal="true"
          class="fui-legacy-sign-in-recovery-modal__card fui-card"
          role="dialog"
        >
          <div class="fui-legacy-sign-in-recovery-modal__eyebrow">Account Found</div>
          <div class="fui-legacy-sign-in-recovery-modal__content">
            <p class="fui-legacy-sign-in-recovery-modal__prompt">{{ recoveryPromptLabel() }}</p>
            <p class="fui-card__subtitle">{{ selectMethodLabel() }}</p>
          </div>
          <div class="fui-screen__children">
            @if (canOfferMethod("google.com")) {
              <fui-google-sign-in-button (signIn)="clearRecovery()" />
            }
            @if (canOfferMethod("github.com")) {
              <fui-github-sign-in-button (signIn)="clearRecovery()" />
            }
            @if (canOfferMethod("facebook.com")) {
              <fui-facebook-sign-in-button (signIn)="clearRecovery()" />
            }
            @if (canOfferMethod("apple.com")) {
              <fui-apple-sign-in-button (signIn)="clearRecovery()" />
            }
            @if (canOfferMethod("microsoft.com")) {
              <fui-microsoft-sign-in-button (signIn)="clearRecovery()" />
            }
            @if (canOfferMethod("twitter.com")) {
              <fui-twitter-sign-in-button (signIn)="clearRecovery()" />
            }
            @if (canOfferMethod("yahoo.com")) {
              <fui-yahoo-sign-in-button (signIn)="clearRecovery()" />
            }
          </div>
          <div class="fui-legacy-sign-in-recovery-modal__notes">
            @if (hasMethod("password")) {
              <p>{{ emailPasswordLabel() }}</p>
            }
            @if (hasMethod("emailLink")) {
              <p>{{ emailLinkLabel() }}</p>
            }
          </div>
          <button fui-button type="button" variant="secondary" (click)="clearRecovery()">
            {{ dismissLabel() }}
          </button>
        </div>
      </div>
    }
  `,
})
/**
 * Displays default recovery UI for legacy sign-in method suggestions.
 */
export class LegacySignInRecoveryComponent {
  recovery = injectLegacySignInRecovery();
  private clearLegacyRecovery = injectClearLegacySignInRecovery();
  recoveryPromptTemplate = injectTranslation("messages", "legacySignInRecoveryPrompt" as never);
  selectMethodText = injectTranslation("messages", "legacySignInRecoverySelectMethod" as never);
  emailPasswordText = injectTranslation("messages", "legacySignInRecoveryEmailPassword" as never);
  emailLinkText = injectTranslation("messages", "legacySignInRecoveryEmailLink" as never);
  dismissText = injectTranslation("labels", "dismiss" as never);

  recoveryPromptLabel() {
    const recovery = this.recovery();
    if (!recovery) {
      return "";
    }

    return this.recoveryPromptTemplate().replace("{email}", recovery.email);
  }

  selectMethodLabel() {
    return this.selectMethodText();
  }

  emailPasswordLabel() {
    return this.emailPasswordText();
  }

  emailLinkLabel() {
    return this.emailLinkText();
  }

  dismissLabel() {
    return this.dismissText();
  }

  hasMethod(method: string) {
    return this.recovery()?.signInMethods.includes(method) ?? false;
  }

  /**
   * Whether an OAuth sign-in button should be offered for `method`.
   *
   * Excludes `attemptedProviderId` defensively so the recovery UI never re-offers the exact
   * provider the user just failed with, even if Firebase's API were to include it in
   * `signInMethods` under some edge case.
   */
  canOfferMethod(method: string) {
    const recovery = this.recovery();
    return (recovery?.signInMethods.includes(method) ?? false) && method !== recovery?.attemptedProviderId;
  }

  clearRecovery() {
    this.clearLegacyRecovery();
  }

  handleBackdropClick(event: MouseEvent) {
    if (event.target === event.currentTarget) {
      this.clearRecovery();
    }
  }

  @HostListener("document:keydown.escape")
  onEscapeKey() {
    if (this.recovery()) {
      this.clearRecovery();
    }
  }
}

// packages/react/src/components/legacy-sign-in-recovery.tsx
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

"use client";

import { getTranslation } from "@firebase-oss/ui-core";
import { useCallback, useEffect, useId } from "react";
import { AppleSignInButton } from "~/auth/oauth/apple-sign-in-button";
import { FacebookSignInButton } from "~/auth/oauth/facebook-sign-in-button";
import { GitHubSignInButton } from "~/auth/oauth/github-sign-in-button";
import { GoogleSignInButton } from "~/auth/oauth/google-sign-in-button";
import { MicrosoftSignInButton } from "~/auth/oauth/microsoft-sign-in-button";
import { TwitterSignInButton } from "~/auth/oauth/twitter-sign-in-button";
import { YahooSignInButton } from "~/auth/oauth/yahoo-sign-in-button";
import { useLegacySignInRecovery, useUI } from "~/hooks";
import { Button } from "./button";

function hasMethod(signInMethods: string[], method: string) {
  return signInMethods.includes(method);
}

/**
 * Whether an OAuth sign-in button should be offered for `method`.
 *
 * Excludes `attemptedProviderId` defensively so the recovery UI never re-offers the exact
 * provider the user just failed with, even if Firebase's API were to include it in
 * `signInMethods` under some edge case.
 */
function canOfferMethod(recovery: { signInMethods: string[]; attemptedProviderId?: string }, method: string) {
  return hasMethod(recovery.signInMethods, method) && method !== recovery.attemptedProviderId;
}

/**
 * Displays default recovery UI for legacy sign-in method suggestions.
 *
 * Returns null if there is no recovery state.
 */
export function LegacySignInRecovery() {
  const ui = useUI();
  const { recovery, clearRecovery } = useLegacySignInRecovery();
  const descriptionId = useId();
  const handleRecoverySignIn = useCallback(() => {
    clearRecovery();
  }, [clearRecovery]);
  const handleBackdropClick = useCallback(
    (event: React.MouseEvent<HTMLDivElement>) => {
      if (event.target === event.currentTarget) {
        clearRecovery();
      }
    },
    [clearRecovery]
  );

  useEffect(() => {
    if (!recovery) {
      return;
    }

    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        clearRecovery();
      }
    };

    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [recovery, clearRecovery]);

  if (!recovery) {
    return null;
  }

  return (
    <div className="fui-legacy-sign-in-recovery-modal" onClick={handleBackdropClick}>
      <div
        aria-describedby={descriptionId}
        aria-label={getTranslation(ui, "messages", "legacySignInRecoverySelectMethod")}
        aria-modal="true"
        className="fui-legacy-sign-in-recovery-modal__card fui-card"
        role="dialog"
      >
        <div className="fui-legacy-sign-in-recovery-modal__eyebrow">Account Found</div>
        <div className="fui-legacy-sign-in-recovery-modal__content">
          <p className="fui-legacy-sign-in-recovery-modal__prompt">
            {getTranslation(ui, "messages", "legacySignInRecoveryPrompt", { email: recovery.email })}
          </p>
          <p className="fui-card__subtitle" id={descriptionId}>
            {getTranslation(ui, "messages", "legacySignInRecoverySelectMethod")}
          </p>
        </div>
        <div className="fui-screen__children">
          {canOfferMethod(recovery, "google.com") ? <GoogleSignInButton onSignIn={handleRecoverySignIn} /> : null}
          {canOfferMethod(recovery, "github.com") ? <GitHubSignInButton onSignIn={handleRecoverySignIn} /> : null}
          {canOfferMethod(recovery, "facebook.com") ? <FacebookSignInButton onSignIn={handleRecoverySignIn} /> : null}
          {canOfferMethod(recovery, "apple.com") ? <AppleSignInButton onSignIn={handleRecoverySignIn} /> : null}
          {canOfferMethod(recovery, "microsoft.com") ? <MicrosoftSignInButton onSignIn={handleRecoverySignIn} /> : null}
          {canOfferMethod(recovery, "twitter.com") ? <TwitterSignInButton onSignIn={handleRecoverySignIn} /> : null}
          {canOfferMethod(recovery, "yahoo.com") ? <YahooSignInButton onSignIn={handleRecoverySignIn} /> : null}
        </div>
        <div className="fui-legacy-sign-in-recovery-modal__notes">
          {hasMethod(recovery.signInMethods, "password") ? (
            <p>{getTranslation(ui, "messages", "legacySignInRecoveryEmailPassword")}</p>
          ) : null}
          {hasMethod(recovery.signInMethods, "emailLink") ? (
            <p>{getTranslation(ui, "messages", "legacySignInRecoveryEmailLink")}</p>
          ) : null}
        </div>
        <Button type="button" variant="secondary" onClick={clearRecovery}>
          {getTranslation(ui, "labels", "dismiss")}
        </Button>
      </div>
    </div>
  );
}
