// examples/angular/src/app/auth/forgot-password/forgot-password.component.ts
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, OnInit, inject } from "@angular/core";
import { CommonModule } from "@angular/common";
import { Router, RouterModule } from "@angular/router";
import { Auth, User, authState } from "@angular/fire/auth";
import { ForgotPasswordAuthScreenComponent } from "@firebase-ui/angular";

@Component({
  selector: "app-forgot-password",
  standalone: true,
  imports: [CommonModule, RouterModule, ForgotPasswordAuthScreenComponent],
  template: `<fui-forgot-password-auth-screen (backToSignIn)="backToSignIn()"></fui-forgot-password-auth-screen> `,
  styles: [],
})
export class ForgotPasswordComponent implements OnInit {
  private auth = inject(Auth);
  private router = inject(Router);

  ngOnInit() {
    // Check if user is already authenticated and redirect to home page
    authState(this.auth).subscribe((user: User | null) => {
      if (user) {
        this.router.navigate(["/"]);
      }
    });
  }

  backToSignIn() {
    this.router.navigate(["/sign-in"]);
  }
}

// examples/nextjs/app/forgot-password/page.tsx
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

"use client";
import { useUser } from "@/lib/firebase/hooks";
import { redirect } from "next/navigation";
import ForgotPasswordScreen from "./screen";

export default async function ForgotPasswordPage() {
  const user = await useUser();

  if (user) {
    return redirect("/");
  }

  return <ForgotPasswordScreen />;
}
