// packages/angular/src/lib/auth/forms/multi-factor-auth-enrollment-form.ts
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, signal, input, output } from "@angular/core";
import { CommonModule } from "@angular/common";
import { FactorId } from "firebase/auth";
import { injectTranslation } from "../../provider";
import { SmsMultiFactorEnrollmentFormComponent } from "./mfa/sms-multi-factor-enrollment-form";
import { TotpMultiFactorEnrollmentFormComponent } from "./mfa/totp-multi-factor-enrollment-form";
import { ButtonComponent } from "../../components/button";

type Hint = (typeof FactorId)[keyof typeof FactorId];

@Component({
  selector: "fui-multi-factor-auth-enrollment-form",
  standalone: true,
  imports: [
    CommonModule,
    SmsMultiFactorEnrollmentFormComponent,
    TotpMultiFactorEnrollmentFormComponent,
    ButtonComponent,
  ],
  template: `
    <div class="fui-content">
      @if (selectedHint()) {
        @if (selectedHint() === "phone") {
          <fui-sms-multi-factor-enrollment-form (onEnrollment)="onEnrollment.emit()" />
        } @else if (selectedHint() === "totp") {
          <fui-totp-multi-factor-enrollment-form (onEnrollment)="onEnrollment.emit()" />
        }
      } @else {
        @for (hint of hints(); track hint) {
          @if (hint === "phone") {
            <button fui-button (click)="selectHint('phone')">
              {{ smsVerificationLabel() }}
            </button>
          } @else if (hint === "totp") {
            <button fui-button (click)="selectHint('totp')">
              {{ totpVerificationLabel() }}
            </button>
          }
        }
      }
    </div>
  `,
})
export class MultiFactorAuthEnrollmentFormComponent {
  hints = input<Hint[]>([FactorId.TOTP, FactorId.PHONE]);
  onEnrollment = output<void>();

  selectedHint = signal<Hint | undefined>(undefined);

  smsVerificationLabel = injectTranslation("labels", "mfaSmsVerification");
  totpVerificationLabel = injectTranslation("labels", "mfaTotpVerification");

  constructor() {
    // If only a single hint is provided, select it by default to improve UX
    const hints = this.hints();
    if (hints.length === 1) {
      this.selectedHint.set(hints[0]);
    } else if (hints.length === 0) {
      throw new Error("MultiFactorAuthEnrollmentForm must have at least one hint");
    }
  }

  selectHint(hint: Hint) {
    this.selectedHint.set(hint);
  }
}

// packages/shadcn/src/components/multi-factor-auth-enrollment-form.tsx
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

"use client";

import { type ComponentProps, useState } from "react";
import { FactorId } from "firebase/auth";
import { getTranslation } from "@firebase-oss/ui-core";
import { useUI } from "@firebase-oss/ui-react";

import { SmsMultiFactorEnrollmentForm } from "@/components/sms-multi-factor-enrollment-form";
import { TotpMultiFactorEnrollmentForm } from "@/components/totp-multi-factor-enrollment-form";
import { Button } from "@/components/ui/button";

type Hint = (typeof FactorId)[keyof typeof FactorId];

export type MultiFactorAuthEnrollmentFormProps = {
  onEnrollment?: () => void;
  hints?: Hint[];
};

const DEFAULT_HINTS = [FactorId.TOTP, FactorId.PHONE] as const;

export function MultiFactorAuthEnrollmentForm(props: MultiFactorAuthEnrollmentFormProps) {
  const hints = props.hints ?? DEFAULT_HINTS;

  if (hints.length === 0) {
    throw new Error("MultiFactorAuthEnrollmentForm must have at least one hint");
  }

  // If only a single hint is provided, select it by default to improve UX.
  const [hint, setHint] = useState<Hint | undefined>(hints.length === 1 ? hints[0] : undefined);

  if (hint) {
    if (hint === FactorId.TOTP) {
      return <TotpMultiFactorEnrollmentForm onSuccess={props.onEnrollment} />;
    }

    if (hint === FactorId.PHONE) {
      return <SmsMultiFactorEnrollmentForm onSuccess={props.onEnrollment} />;
    }

    throw new Error(`Unknown multi-factor enrollment type: ${hint}`);
  }

  return (
    <div className="flex flex-col gap-2">
      {hints.map((hint) => {
        if (hint === FactorId.TOTP) {
          return <TotpButton key={hint} onClick={() => setHint(hint)} />;
        }

        if (hint === FactorId.PHONE) {
          return <SmsButton key={hint} onClick={() => setHint(hint)} />;
        }

        return null;
      })}
    </div>
  );
}

function TotpButton(props: ComponentProps<typeof Button>) {
  const ui = useUI();
  const labelText = getTranslation(ui, "labels", "mfaTotpVerification");
  return (
    <Button {...props} variant="outline">
      {labelText}
    </Button>
  );
}

function SmsButton(props: ComponentProps<typeof Button>) {
  const ui = useUI();
  const labelText = getTranslation(ui, "labels", "mfaSmsVerification");
  return (
    <Button {...props} variant="outline">
      {labelText}
    </Button>
  );
}
