// packages/angular/src/lib/auth/forms/phone-auth-form.ts
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, ElementRef, effect, input, signal, output, computed, viewChild } from "@angular/core";
import { CommonModule } from "@angular/common";
import { injectForm, injectStore, TanStackAppField, TanStackField } from "@tanstack/angular-form";
import {
  injectPhoneAuthFormSchema,
  injectPhoneAuthVerifyFormSchema,
  injectRecaptchaVerifier,
  injectTranslation,
  injectUI,
} from "../../provider";
import { RecaptchaVerifier, UserCredential } from "@angular/fire/auth";
import { PoliciesComponent } from "../../components/policies";
import { CountrySelectorComponent } from "../../components/country-selector";
import { FormInputComponent, FormSubmitComponent, FormErrorMessageComponent } from "../../components/form";
import {
  countryData,
  FirebaseUIError,
  formatPhoneNumber,
  confirmPhoneNumber,
  verifyPhoneNumber,
  CountryCode,
} from "@invertase/firebaseui-core";

@Component({
  selector: "fui-phone-number-form",
  standalone: true,
  imports: [
    CommonModule,
    TanStackField,
    TanStackAppField,
    PoliciesComponent,
    FormInputComponent,
    FormSubmitComponent,
    FormErrorMessageComponent,
    CountrySelectorComponent,
  ],
  template: `
    <form (submit)="handleSubmit($event)" class="fui-form">
      <fieldset>
        <fui-country-selector [(value)]="country"></fui-country-selector>
        <fui-form-input
          name="phoneNumber"
          tanstack-app-field
          [tanstackField]="form"
          [label]="phoneNumberLabel()"
          type="tel"
        ></fui-form-input>
      </fieldset>
      <fieldset>
        <div class="fui-recaptcha-container" #recaptchaContainer></div>
      </fieldset>
      <fui-policies />
      <fieldset>
        <fui-form-submit [state]="state()">
          {{ sendCodeLabel() }}
        </fui-form-submit>
        <fui-form-error-message [state]="state()" />
      </fieldset>
    </form>
  `,
})
export class PhoneNumberFormComponent {
  private ui = injectUI();
  private formSchema = injectPhoneAuthFormSchema();

  onSubmit = output<{ verificationId: string; phoneNumber: string }>();
  country = signal<CountryCode>(countryData[0].code);

  phoneNumberLabel = injectTranslation("labels", "phoneNumber");
  sendCodeLabel = injectTranslation("labels", "sendCode");
  unknownErrorLabel = injectTranslation("errors", "unknownError");

  recaptchaContainer = viewChild.required<ElementRef<HTMLDivElement>>("recaptchaContainer");
  recaptchaVerifier = injectRecaptchaVerifier(() => this.recaptchaContainer());

  form = injectForm({
    defaultValues: {
      phoneNumber: "",
    },
  });

  state = injectStore(this.form, (state) => state);

  constructor() {
    effect(() => {
      this.form.update({
        validators: {
          onBlur: this.formSchema(),
          onSubmitAsync: async ({ value }) => {
            const selectedCountry = countryData.find((c) => c.code === this.country());
            const formattedNumber = formatPhoneNumber(value.phoneNumber, selectedCountry!);

            try {
              const verifier = this.recaptchaVerifier();
              if (!verifier) {
                return this.unknownErrorLabel();
              }
              const verificationId = await verifyPhoneNumber(this.ui(), formattedNumber, verifier);
              this.onSubmit.emit({ verificationId, phoneNumber: formattedNumber });
              return;
            } catch (error) {
              if (error instanceof FirebaseUIError) {
                return error.message;
              }

              return this.unknownErrorLabel();
            }
          },
        },
      });
    });

    effect((onCleanup) => {
      const verifier = this.recaptchaVerifier();

      onCleanup(() => {
        if (verifier) {
          verifier.clear();
        }
      });
    });
  }

  async handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    event.stopPropagation();
    this.form.handleSubmit();
  }
}

@Component({
  selector: "fui-verification-form",
  standalone: true,
  imports: [
    CommonModule,
    TanStackField,
    TanStackAppField,
    PoliciesComponent,
    FormInputComponent,
    FormSubmitComponent,
    FormErrorMessageComponent,
  ],
  template: `
    <form (submit)="handleSubmit($event)" class="fui-form">
      <fieldset>
        <fui-form-input
          name="verificationCode"
          tanstack-app-field
          [tanstackField]="form"
          [label]="verificationCodeLabel()"
          [description]="smsVerificationPrompt()"
          type="text"
        ></fui-form-input>
      </fieldset>

      <fui-policies />

      <fieldset>
        <fui-form-submit [state]="state()">
          {{ verifyCodeLabel() }}
        </fui-form-submit>
        <fui-form-error-message [state]="state()" />
      </fieldset>
    </form>
  `,
})
export class VerificationFormComponent {
  private ui = injectUI();
  private formSchema = injectPhoneAuthVerifyFormSchema();

  verificationId = input.required<string>();
  signIn = output<UserCredential>();

  verificationCodeLabel = injectTranslation("labels", "verificationCode");
  verifyCodeLabel = injectTranslation("labels", "verifyCode");
  smsVerificationPrompt = injectTranslation("prompts", "smsVerificationPrompt");
  unknownErrorLabel = injectTranslation("errors", "unknownError");

  form = injectForm({
    defaultValues: {
      verificationId: "",
      verificationCode: "",
    },
  });

  state = injectStore(this.form, (state) => state);

  constructor() {
    effect(() => {
      this.form.setFieldValue("verificationId", this.verificationId());
    });

    effect(() => {
      this.form.update({
        validators: {
          onBlur: this.formSchema(),
          onSubmitAsync: async ({ value }) => {
            try {
              const credential = await confirmPhoneNumber(this.ui(), this.verificationId(), value.verificationCode);
              this.signIn.emit(credential);
              return;
            } catch (error) {
              if (error instanceof FirebaseUIError) {
                return error.message;
              }

              return this.unknownErrorLabel();
            }
          },
        },
      });
    });
  }

  async handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    event.stopPropagation();
    this.form.handleSubmit();
  }
}

@Component({
  selector: "fui-phone-auth-form",
  standalone: true,
  imports: [CommonModule, PhoneNumberFormComponent, VerificationFormComponent],
  template: `
    <div class="fui-form-container">
      @if (verificationId()) {
        <fui-verification-form [verificationId]="verificationId()!" (signIn)="signIn.emit($event)" />
      } @else {
        <fui-phone-number-form (onSubmit)="handlePhoneSubmit($event)" />
      }
    </div>
  `,
})
export class PhoneAuthFormComponent {
  verificationId = signal<string | null>(null);
  signIn = output<UserCredential>();

  handlePhoneSubmit(data: { verificationId: string; phoneNumber: string }) {
    this.verificationId.set(data.verificationId);
  }
}

// packages/shadcn/src/components/phone-auth-form.tsx
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

"use client";

import {
  type PhoneAuthFormProps,
  usePhoneAuthNumberFormSchema,
  usePhoneAuthVerifyFormSchema,
  usePhoneNumberFormAction,
  useRecaptchaVerifier,
  useUI,
  useVerifyPhoneNumberFormAction,
} from "@invertase/firebaseui-react";
import { useState } from "react";
import type { UserCredential } from "firebase/auth";
import { useRef } from "react";
import { useForm } from "react-hook-form";
import { standardSchemaResolver } from "@hookform/resolvers/standard-schema";
import {
  FirebaseUIError,
  formatPhoneNumber,
  getTranslation,
  type PhoneAuthNumberFormSchema,
  type PhoneAuthVerifyFormSchema,
} from "@invertase/firebaseui-core";

import { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Policies } from "@/components/policies";
import { CountrySelector, type CountrySelectorRef } from "@/components/country-selector";
import { InputOTP, InputOTPGroup, InputOTPSlot } from "@/components/ui/input-otp";

type VerifyPhoneNumberFormProps = {
  verificationId: string;
  onSuccess: (credential: UserCredential) => void;
};

function VerifyPhoneNumberForm(props: VerifyPhoneNumberFormProps) {
  const ui = useUI();
  const schema = usePhoneAuthVerifyFormSchema();
  const action = useVerifyPhoneNumberFormAction();

  const form = useForm<PhoneAuthVerifyFormSchema>({
    resolver: standardSchemaResolver(schema),
    defaultValues: {
      verificationId: props.verificationId,
      verificationCode: "",
    },
  });

  async function onSubmit(values: PhoneAuthVerifyFormSchema) {
    try {
      const credential = await action(values);
      props.onSuccess(credential);
    } catch (error) {
      const message = error instanceof FirebaseUIError ? error.message : String(error);
      form.setError("root", { message });
    }
  }

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="flex flex-col gap-4">
        <FormField
          control={form.control}
          name="verificationCode"
          render={({ field }) => (
            <FormItem>
              <FormLabel>{getTranslation(ui, "labels", "verificationCode")}</FormLabel>
              <FormDescription>{getTranslation(ui, "prompts", "smsVerificationPrompt")}</FormDescription>
              <FormControl>
                <InputOTP maxLength={6} {...field}>
                  <InputOTPGroup>
                    <InputOTPSlot index={0} />
                    <InputOTPSlot index={1} />
                    <InputOTPSlot index={2} />
                    <InputOTPSlot index={3} />
                    <InputOTPSlot index={4} />
                    <InputOTPSlot index={5} />
                  </InputOTPGroup>
                </InputOTP>
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        <Button type="submit" disabled={ui.state !== "idle"}>
          {getTranslation(ui, "labels", "verifyCode")}
        </Button>
        {form.formState.errors.root && <FormMessage>{form.formState.errors.root.message}</FormMessage>}
      </form>
    </Form>
  );
}

type PhoneNumberFormProps = {
  onSubmit: (verificationId: string) => void;
};

function PhoneNumberForm(props: PhoneNumberFormProps) {
  const ui = useUI();
  const recaptchaContainerRef = useRef<HTMLDivElement>(null);
  const recaptchaVerifier = useRecaptchaVerifier(recaptchaContainerRef);
  const countrySelector = useRef<CountrySelectorRef>(null);
  const action = usePhoneNumberFormAction();
  const schema = usePhoneAuthNumberFormSchema();

  const form = useForm<PhoneAuthNumberFormSchema>({
    resolver: standardSchemaResolver(schema),
    defaultValues: {
      phoneNumber: "",
    },
  });

  async function onSubmit(values: PhoneAuthNumberFormSchema) {
    try {
      const formatted = formatPhoneNumber(values.phoneNumber, countrySelector.current!.getCountry());
      const verificationId = await action({ phoneNumber: formatted, recaptchaVerifier: recaptchaVerifier! });
      props.onSubmit(verificationId);
    } catch (error) {
      const message = error instanceof FirebaseUIError ? error.message : String(error);
      form.setError("root", { message });
    }
  }

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="flex flex-col gap-4">
        <FormField
          control={form.control}
          name="phoneNumber"
          render={({ field }) => (
            <FormItem>
              <FormLabel>{getTranslation(ui, "labels", "phoneNumber")}</FormLabel>
              <FormControl>
                <div className="flex items-center gap-2">
                  <CountrySelector ref={countrySelector} />
                  <Input {...field} type="tel" />
                </div>
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        <div ref={recaptchaContainerRef} />
        <Policies />
        <Button type="submit" disabled={ui.state !== "idle"}>
          {getTranslation(ui, "labels", "sendCode")}
        </Button>
        {form.formState.errors.root && <FormMessage>{form.formState.errors.root.message}</FormMessage>}
      </form>
    </Form>
  );
}

export type { PhoneAuthFormProps };

export function PhoneAuthForm(props: PhoneAuthFormProps) {
  const [verificationId, setVerificationId] = useState<string | null>(null);

  if (!verificationId) {
    return <PhoneNumberForm onSubmit={setVerificationId} />;
  }

  return (
    <VerifyPhoneNumberForm
      verificationId={verificationId}
      onSuccess={(credential) => {
        props.onSignIn?.(credential);
      }}
    />
  );
}
