// packages/angular/src/lib/auth/forms/sign-up-auth-form.ts
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, output, effect, computed } from "@angular/core";
import { CommonModule } from "@angular/common";
import { injectForm, injectStore, TanStackAppField, TanStackField } from "@tanstack/angular-form";
import { FirebaseUIError, createUserWithEmailAndPassword, hasBehavior } from "@firebase-ui/core";
import { UserCredential } from "@angular/fire/auth";

import { PoliciesComponent } from "../../components/policies";
import { injectSignUpAuthFormSchema, injectTranslation, injectUI } from "../../provider";
import {
  FormInputComponent,
  FormSubmitComponent,
  FormErrorMessageComponent,
  FormActionComponent,
} from "../../components/form";

@Component({
  selector: "fui-sign-up-auth-form",
  imports: [
    CommonModule,
    TanStackField,
    TanStackAppField,
    PoliciesComponent,
    FormInputComponent,
    FormSubmitComponent,
    FormErrorMessageComponent,
    FormActionComponent,
  ],
  template: `
    <form (submit)="handleSubmit($event)" class="fui-form">
      @if (requireDisplayNameField()) {
        <fieldset>
          <fui-form-input
            name="displayName"
            tanstack-app-field
            [tanstackField]="form"
            label="{{ displayNameLabel() }}"
          />
        </fieldset>
      }
      <fieldset>
        <fui-form-input name="email" tanstack-app-field [tanstackField]="form" label="{{ emailLabel() }}" />
      </fieldset>
      <fieldset>
        <fui-form-input
          name="password"
          tanstack-app-field
          [tanstackField]="form"
          label="{{ passwordLabel() }}"
          type="password"
        />
      </fieldset>
      <fui-policies />
      <fieldset>
        <fui-form-submit [state]="state()">
          {{ createAccountLabel() }}
        </fui-form-submit>
        <fui-form-error-message [state]="state()" />
      </fieldset>

      @if (signIn) {
        <button fui-form-action (click)="signIn.emit()">{{ haveAccountLabel() }} {{ signInLabel() }} &rarr;</button>
      }
    </form>
  `,
  standalone: true,
})
export class SignUpAuthFormComponent {
  private ui = injectUI();
  private formSchema = injectSignUpAuthFormSchema();

  requireDisplayNameField = computed(() => {
    return hasBehavior(this.ui(), "requireDisplayName");
  });

  emailLabel = injectTranslation("labels", "emailAddress");
  displayNameLabel = injectTranslation("labels", "displayName");
  passwordLabel = injectTranslation("labels", "password");
  createAccountLabel = injectTranslation("labels", "createAccount");
  haveAccountLabel = injectTranslation("prompts", "haveAccount");
  signInLabel = injectTranslation("labels", "signIn");
  unknownErrorLabel = injectTranslation("errors", "unknownError");

  signUp = output<UserCredential>();
  signIn = output<void>();

  form = injectForm({
    defaultValues: {
      email: "",
      password: "",
      displayName: this.requireDisplayNameField() ? "" : undefined,
    },
  });

  state = injectStore(this.form, (state) => state);

  handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    event.stopPropagation();
    this.form.handleSubmit();
  }

  constructor() {
    effect(() => {
      this.form.update({
        validators: {
          onBlur: this.formSchema(),
          onSubmit: this.formSchema(),
          onSubmitAsync: async ({ value }) => {
            try {
              const credential = await createUserWithEmailAndPassword(
                this.ui(),
                value.email,
                value.password,
                value.displayName
              );
              this.signUp?.emit(credential);
              return;
            } catch (error) {
              if (error instanceof FirebaseUIError) {
                return error.message;
              }

              return this.unknownErrorLabel();
            }
          },
        },
      });
    });
  }
}

// packages/shadcn/src/components/sign-up-auth-form.tsx
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

"use client";

import type { SignUpAuthFormSchema } from "@firebase-oss/ui-core";
import {
  useSignUpAuthFormAction,
  useSignUpAuthFormSchema,
  useUI,
  type SignUpAuthFormProps,
  useRequireDisplayName,
} from "@firebase-oss/ui-react";
import { useForm } from "react-hook-form";
import { standardSchemaResolver } from "@hookform/resolvers/standard-schema";
import { FirebaseUIError, getTranslation } from "@firebase-oss/ui-core";

import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Policies } from "./policies";

export type { SignUpAuthFormProps };

export function SignUpAuthForm(props: SignUpAuthFormProps) {
  const ui = useUI();
  const schema = useSignUpAuthFormSchema();
  const action = useSignUpAuthFormAction();
  const requireDisplayName = useRequireDisplayName();

  const form = useForm<SignUpAuthFormSchema>({
    resolver: standardSchemaResolver(schema),
    defaultValues: {
      email: "",
      password: "",
      displayName: requireDisplayName ? "" : undefined,
    },
  });

  async function onSubmit(values: SignUpAuthFormSchema) {
    try {
      const credential = await action(values);
      props.onSignUp?.(credential);
    } catch (error) {
      const message = error instanceof FirebaseUIError ? error.message : String(error);
      form.setError("root", { message });
    }
  }

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="flex flex-col gap-y-4">
        {requireDisplayName ? (
          <FormField
            control={form.control}
            name="displayName"
            render={({ field }) => (
              <FormItem>
                <FormLabel>{getTranslation(ui, "labels", "displayName")}</FormLabel>
                <FormControl>
                  <Input {...field} />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
        ) : null}
        <FormField
          control={form.control}
          name="email"
          render={({ field }) => (
            <FormItem>
              <FormLabel>{getTranslation(ui, "labels", "emailAddress")}</FormLabel>
              <FormControl>
                <Input {...field} type="email" />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="password"
          render={({ field }) => (
            <FormItem>
              <FormLabel>{getTranslation(ui, "labels", "password")}</FormLabel>
              <FormControl>
                <Input {...field} type="password" />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        <Policies />
        <Button type="submit" disabled={ui.state !== "idle"}>
          {getTranslation(ui, "labels", "createAccount")}
        </Button>
        {form.formState.errors.root && <FormMessage>{form.formState.errors.root.message}</FormMessage>}
        {props.onSignInClick ? (
          <Button type="button" variant="link" size="sm" onClick={props.onSignInClick}>
            <span className="text-xs">
              {getTranslation(ui, "prompts", "haveAccount")} {getTranslation(ui, "labels", "signIn")}
            </span>
          </Button>
        ) : null}
      </form>
    </Form>
  );
}
