// packages/angular/src/lib/auth/forms/mfa/sms-multi-factor-assertion-form.ts
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, ElementRef, effect, input, signal, output, computed, viewChild } from "@angular/core";
import { CommonModule } from "@angular/common";
import { injectForm, injectStore, TanStackAppField, TanStackField } from "@tanstack/angular-form";
import {
  injectMultiFactorPhoneAuthVerifyFormSchema,
  injectRecaptchaVerifier,
  injectTranslation,
  injectUI,
} from "../../../provider";
import { FormInputComponent, FormSubmitComponent, FormErrorMessageComponent } from "../../../components/form";
import { FirebaseUIError, verifyPhoneNumber, signInWithMultiFactorAssertion, getTranslation } from "@invertase/firebaseui-core";
import { PhoneAuthProvider, PhoneMultiFactorGenerator, type MultiFactorInfo, type UserCredential } from "firebase/auth";

type PhoneMultiFactorInfo = MultiFactorInfo & {
  phoneNumber?: string;
};

@Component({
  selector: "fui-sms-multi-factor-assertion-phone-form",
  standalone: true,
  imports: [
    CommonModule,
    FormSubmitComponent,
    FormErrorMessageComponent,
  ],
  template: `
    <form (submit)="handleSubmit($event)" class="fui-form">
      <fieldset>
        <label>
          <div data-input-description>
            {{ mfaSmsAssertionPrompt() }}
          </div>
        </label>
      </fieldset>
      <fieldset>
        <div class="fui-recaptcha-container" #recaptchaContainer></div>
      </fieldset>
      <fieldset>
        <fui-form-submit [state]="state()">
          {{ sendCodeLabel() }}
        </fui-form-submit>
        <fui-form-error-message [state]="state()" />
      </fieldset>
    </form>
  `,
})
export class SmsMultiFactorAssertionPhoneFormComponent {
  private ui = injectUI();

  hint = input.required<MultiFactorInfo>();
  onSubmit = output<string>();

  sendCodeLabel = injectTranslation("labels", "sendCode");

  recaptchaContainer = viewChild.required<ElementRef<HTMLDivElement>>("recaptchaContainer");

  phoneNumber = computed(() => {
    const hint = this.hint() as PhoneMultiFactorInfo;
    return hint.phoneNumber || "";
  });

  mfaSmsAssertionPrompt = computed(() => {
    return getTranslation(
      this.ui(),
      "messages",
      "mfaSmsAssertionPrompt",
      { phoneNumber: this.phoneNumber() }
    );
  });

  recaptchaVerifier = injectRecaptchaVerifier(() => this.recaptchaContainer());

  form = injectForm({
    defaultValues: {},
  });

  state = injectStore(this.form, (state) => state);

  constructor() {
    effect(() => {
      this.form.update({
        validators: {
          onSubmitAsync: async () => {
            try {
              const verifier = this.recaptchaVerifier();
              if (!verifier) {
                return "Recaptcha verifier not available";
              }

              const verificationId = await verifyPhoneNumber(this.ui(), "", verifier, undefined, this.hint());
              this.onSubmit.emit(verificationId);
              return;
            } catch (error) {
              return error instanceof FirebaseUIError ? error.message : String(error);
            }
          },
        },
      });
    });

    effect((onCleanup) => {
      const verifier = this.recaptchaVerifier();
      onCleanup(() => {
        if (verifier) {
          verifier.clear();
        }
      });
    });
  }

  async handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    event.stopPropagation();
    this.form.handleSubmit();
  }
}

@Component({
  selector: "fui-sms-multi-factor-assertion-verify-form",
  standalone: true,
  imports: [
    CommonModule,
    TanStackField,
    TanStackAppField,
    FormInputComponent,
    FormSubmitComponent,
    FormErrorMessageComponent,
  ],
  template: `
    <form (submit)="handleSubmit($event)" class="fui-form">
      <fieldset>
        <fui-form-input
          name="verificationCode"
          tanstack-app-field
          [tanstackField]="form"
          [label]="verificationCodeLabel()"
          [description]="smsVerificationPrompt()"
          type="text"
        ></fui-form-input>
      </fieldset>
      <fieldset>
        <fui-form-submit [state]="state()">
          {{ verifyCodeLabel() }}
        </fui-form-submit>
        <fui-form-error-message [state]="state()" />
      </fieldset>
    </form>
  `,
})
export class SmsMultiFactorAssertionVerifyFormComponent {
  private ui = injectUI();
  private formSchema = injectMultiFactorPhoneAuthVerifyFormSchema();

  verificationId = input.required<string>();
  onSuccess = output<UserCredential>();

  verificationCodeLabel = injectTranslation("labels", "verificationCode");
  verifyCodeLabel = injectTranslation("labels", "verifyCode");
  smsVerificationPrompt = injectTranslation("prompts", "smsVerificationPrompt");
  unknownErrorLabel = injectTranslation("errors", "unknownError");

  form = injectForm({
    defaultValues: {
      verificationId: "",
      verificationCode: "",
    },
  });

  state = injectStore(this.form, (state) => state);

  constructor() {
    effect(() => {
      this.form.setFieldValue("verificationId", this.verificationId());
    });

    effect(() => {
      this.form.update({
        validators: {
          onBlur: this.formSchema(),
          onSubmit: this.formSchema(),
          onSubmitAsync: async ({ value }) => {
            try {
              const credential = PhoneAuthProvider.credential(value.verificationId, value.verificationCode);
              const assertion = PhoneMultiFactorGenerator.assertion(credential);
              const result = await signInWithMultiFactorAssertion(this.ui(), assertion);
              this.onSuccess.emit(result);
              return;
            } catch (error) {
              return error instanceof FirebaseUIError ? error.message : String(error);
            }
          },
        },
      });
    });
  }

  async handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    event.stopPropagation();
    this.form.handleSubmit();
  }
}

@Component({
  selector: "fui-sms-multi-factor-assertion-form",
  standalone: true,
  imports: [CommonModule, SmsMultiFactorAssertionPhoneFormComponent, SmsMultiFactorAssertionVerifyFormComponent],
  template: `
    <div class="fui-content">
      @if (verification()) {
        <fui-sms-multi-factor-assertion-verify-form
          [verificationId]="verification()!.verificationId"
          (onSuccess)="onSuccess.emit($event)"
        />
      } @else {
        <fui-sms-multi-factor-assertion-phone-form [hint]="hint()" (onSubmit)="handlePhoneSubmit($event)" />
      }
    </div>
  `,
})
export class SmsMultiFactorAssertionFormComponent {
  hint = input.required<MultiFactorInfo>();
  onSuccess = output<UserCredential>();

  verification = signal<{ verificationId: string } | null>(null);

  handlePhoneSubmit(verificationId: string) {
    this.verification.set({ verificationId });
  }
}

// packages/shadcn/src/components/sms-multi-factor-assertion-form.tsx
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

"use client";

import { useRef, useState } from "react";
import { type UserCredential, type MultiFactorInfo } from "firebase/auth";

import { FirebaseUIError, getTranslation } from "@invertase/firebaseui-core";
import {
  useMultiFactorPhoneAuthVerifyFormSchema,
  useRecaptchaVerifier,
  useUI,
  useSmsMultiFactorAssertionPhoneFormAction,
  useSmsMultiFactorAssertionVerifyFormAction,
} from "@invertase/firebaseui-react";
import { useForm } from "react-hook-form";
import { standardSchemaResolver } from "@hookform/resolvers/standard-schema";

import { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Button } from "@/components/ui/button";
import { InputOTP, InputOTPGroup, InputOTPSlot } from "@/components/ui/input-otp";

type PhoneMultiFactorInfo = MultiFactorInfo & {
  phoneNumber?: string;
};

type SmsMultiFactorAssertionPhoneFormProps = {
  hint: MultiFactorInfo;
  onSubmit: (verificationId: string) => void;
};

function SmsMultiFactorAssertionPhoneForm(props: SmsMultiFactorAssertionPhoneFormProps) {
  const ui = useUI();
  const recaptchaContainerRef = useRef<HTMLDivElement>(null);
  const recaptchaVerifier = useRecaptchaVerifier(recaptchaContainerRef);
  const action = useSmsMultiFactorAssertionPhoneFormAction();
  const [error, setError] = useState<string | null>(null);

  const onSubmit = async () => {
    try {
      setError(null);
      const verificationId = await action({ hint: props.hint, recaptchaVerifier: recaptchaVerifier! });
      props.onSubmit(verificationId);
    } catch (error) {
      const message = error instanceof FirebaseUIError ? error.message : String(error);
      setError(message);
    }
  };

  return (
    <div className="space-y-4">
      <FormItem>
        <FormLabel>{getTranslation(ui, "labels", "phoneNumber")}</FormLabel>
        <FormDescription>
          {getTranslation(ui, "messages", "mfaSmsAssertionPrompt", {
            phoneNumber: (props.hint as PhoneMultiFactorInfo).phoneNumber || "",
          })}
        </FormDescription>
      </FormItem>
      <div className="fui-recaptcha-container" ref={recaptchaContainerRef} />
      <Button onClick={onSubmit} disabled={ui.state !== "idle"}>
        {getTranslation(ui, "labels", "sendCode")}
      </Button>
      {error && <div className="text-sm text-red-600">{error}</div>}
    </div>
  );
}

type SmsMultiFactorAssertionVerifyFormProps = {
  verificationId: string;
  onSuccess: (credential: UserCredential) => void;
};

function SmsMultiFactorAssertionVerifyForm(props: SmsMultiFactorAssertionVerifyFormProps) {
  const ui = useUI();
  const schema = useMultiFactorPhoneAuthVerifyFormSchema();
  const action = useSmsMultiFactorAssertionVerifyFormAction();

  const form = useForm<{ verificationId: string; verificationCode: string }>({
    resolver: standardSchemaResolver(schema),
    defaultValues: {
      verificationId: props.verificationId,
      verificationCode: "",
    },
  });

  const onSubmit = async (values: { verificationId: string; verificationCode: string }) => {
    try {
      const credential = await action({
        verificationId: values.verificationId,
        verificationCode: values.verificationCode,
      });
      props.onSuccess(credential);
    } catch (error) {
      const message = error instanceof FirebaseUIError ? error.message : String(error);
      form.setError("root", { message });
    }
  };

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="flex flex-col gap-y-4">
        <FormField
          control={form.control}
          name="verificationCode"
          render={({ field }) => (
            <FormItem>
              <FormLabel>{getTranslation(ui, "labels", "verificationCode")}</FormLabel>
              <FormDescription>{getTranslation(ui, "prompts", "smsVerificationPrompt")}</FormDescription>
              <FormControl>
                <InputOTP maxLength={6} {...field}>
                  <InputOTPGroup>
                    <InputOTPSlot index={0} />
                    <InputOTPSlot index={1} />
                    <InputOTPSlot index={2} />
                    <InputOTPSlot index={3} />
                    <InputOTPSlot index={4} />
                    <InputOTPSlot index={5} />
                  </InputOTPGroup>
                </InputOTP>
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        <Button type="submit" disabled={ui.state !== "idle"}>
          {getTranslation(ui, "labels", "verifyCode")}
        </Button>
        {form.formState.errors.root && <FormMessage>{form.formState.errors.root.message}</FormMessage>}
      </form>
    </Form>
  );
}

export type SmsMultiFactorAssertionFormProps = {
  hint: MultiFactorInfo;
  onSuccess?: (credential: UserCredential) => void;
};

export function SmsMultiFactorAssertionForm(props: SmsMultiFactorAssertionFormProps) {
  const [verification, setVerification] = useState<{
    verificationId: string;
  } | null>(null);

  if (!verification) {
    return (
      <SmsMultiFactorAssertionPhoneForm
        hint={props.hint}
        onSubmit={(verificationId) => setVerification({ verificationId })}
      />
    );
  }

  return (
    <SmsMultiFactorAssertionVerifyForm
      verificationId={verification.verificationId}
      onSuccess={(credential) => {
        props.onSuccess?.(credential);
      }}
    />
  );
}
