// examples/angular/src/app/screens/oauth-screen/oauth-screen.component.ts
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component } from "@angular/core";
import { CommonModule } from "@angular/common";
import { OAuthScreenComponent } from "@invertase/firebaseui-angular";

@Component({
  selector: "app-oauth-screen",
  standalone: true,
  imports: [CommonModule, OAuthScreenComponent],
  template: ` <fui-oauth-screen></fui-oauth-screen> `,
  styles: [],
})
export class OAuthScreenWrapperComponent {}

// examples/nextjs-ssr/app/screens/oauth-screen/page.tsx
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

"use client";

import { GoogleSignInButton, OAuthScreen } from "@invertase/firebaseui-react";

export default function OAuthScreenPage() {
  return (
    <OAuthScreen>
      <GoogleSignInButton />
    </OAuthScreen>
  );
}
