// examples/angular/src/app/screens/phone-auth-screen-w-oauth.ts
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, inject } from "@angular/core";
import { CommonModule } from "@angular/common";
import { PhoneAuthScreenComponent, GoogleSignInButtonComponent, ContentComponent } from "@firebase-oss/ui-angular";
import { Router } from "@angular/router";

@Component({
  selector: "app-phone-auth-screen-w-oauth",
  standalone: true,
  imports: [CommonModule, PhoneAuthScreenComponent, GoogleSignInButtonComponent, ContentComponent],
  template: `
    <fui-phone-auth-screen (signIn)="onSignIn()">
      <fui-content>
        <fui-google-sign-in-button />
      </fui-content>
    </fui-phone-auth-screen>
  `,
  styles: [],
})
export class PhoneAuthScreenWithOAuthComponent {
  private router = inject(Router);

  onSignIn() {
    this.router.navigate(["/"]);
  }
}

// examples/shadcn/src/screens/phone-auth-screen-w-oauth.tsx
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

"use client";

import { GoogleSignInButton } from "@/components/google-sign-in-button";
import { FacebookSignInButton } from "@/components/facebook-sign-in-button";
import { AppleSignInButton } from "@/components/apple-sign-in-button";
import { GitHubSignInButton } from "@/components/github-sign-in-button";
import { MicrosoftSignInButton } from "@/components/microsoft-sign-in-button";
import { TwitterSignInButton } from "@/components/twitter-sign-in-button";
import { PhoneAuthScreen } from "@/components/phone-auth-screen";
import { useNavigate } from "react-router";

export default function PhoneAuthScreenWithOAuthPage() {
  const navigate = useNavigate();

  return (
    <PhoneAuthScreen
      onSignIn={() => {
        navigate("/");
      }}
    >
      <GoogleSignInButton />
      <FacebookSignInButton />
      <AppleSignInButton />
      <GitHubSignInButton />
      <MicrosoftSignInButton />
      <TwitterSignInButton />
    </PhoneAuthScreen>
  );
}
