// packages/angular/src/lib/auth/forms/email-link-auth-form/email-link-auth-form.component.ts
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, OnInit, output } from "@angular/core";
import { CommonModule } from "@angular/common";
import { injectForm, TanStackAppField, TanStackField } from "@tanstack/angular-form";
import { UserCredential } from "@angular/fire/auth";
import {
  FirebaseUIError,
  completeEmailLinkSignIn,
  sendSignInLinkToEmail,
} from "@firebase-ui/core";

import { injectEmailLinkAuthFormSchema, injectTranslation, injectUI } from "../../../provider";
import { PoliciesComponent } from "../../../components/policies/policies.component";
import { FormErrorMessageComponent, FormInputComponent, FormSubmitComponent } from "../../../components/form/form.component";

@Component({
  selector: "fui-email-link-auth-form",
  standalone: true,
  imports: [
    CommonModule,
    PoliciesComponent,
    TanStackField,
    TanStackAppField,
    FormInputComponent,
    FormSubmitComponent,
    FormErrorMessageComponent,
  ],
  template: `
    @if (emailSent) {
      <div class="fui-form">
        {{ emailSentMessage() }}
      </div>
    }

    @if (!emailSent) {
      <form (submit)="handleSubmit($event)" class="fui-form">
        <fieldset>
          <fui-form-input
            name="email"
            tanstack-app-field
            [tanstackField]="form"
            label="{{ emailLabel() }}"
          ></fui-form-input>
        </fieldset>
        <fui-policies />
        <fieldset>
          <fui-form-submit>
            {{ sendSignInLinkLabel() }}
          </fui-form-submit>
          <fui-form-error-message></fui-form-error-message>
        </fieldset>
      </form>
    }
  `,
})
export class EmailLinkAuthFormComponent implements OnInit {
  private ui = injectUI();
  private formSchema = injectEmailLinkAuthFormSchema();

  emailLabel = injectTranslation("labels", "emailAddress");
  sendSignInLinkLabel = injectTranslation("labels", "sendSignInLink");
  emailSentMessage = injectTranslation("messages", "signInLinkSent");
  unknownErrorLabel = injectTranslation("errors", "unknownError");

  emailSent = output<void>();
  signIn = output<UserCredential>();

  form = injectForm({
    defaultValues: {
      email: "",
    },
  });

  handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    event.stopPropagation();
    this.form.handleSubmit();
  }

  async ngOnInit() {
    this.completeSignIn();

    this.form.update({
      validators: {
        onBlur: this.formSchema(),
        onSubmit: this.formSchema(),
        onSubmitAsync: async ({ value }) => {
          try {
            await sendSignInLinkToEmail(this.ui(), value.email);
            this.emailSent?.emit();
          } catch (error) {
            if (error instanceof FirebaseUIError) {
              return error.message;
            }

            return this.unknownErrorLabel();
          }
        },
      },
    });
  }

  private async completeSignIn() {
    const credential = await completeEmailLinkSignIn(this.ui(), window.location.href);

    if (credential) {
      this.signIn?.emit(credential);
    }
  }
}

// packages/react/src/auth/forms/email-link-auth-form.tsx
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

"use client";

import { FirebaseUIError, completeEmailLinkSignIn, getTranslation, sendSignInLinkToEmail } from "@firebase-ui/core";
import type { UserCredential } from "firebase/auth";
import { useEmailLinkAuthFormSchema, useUI } from "~/hooks";
import { form } from "~/components/form";
import { Policies } from "~/components/policies";
import { useCallback, useEffect, useState } from "react";

export type EmailLinkAuthFormProps = {
  onEmailSent?: () => void;
  onSignIn?: (credential: UserCredential) => void;
};

export function useEmailLinkAuthFormAction() {
  const ui = useUI();

  return useCallback(
    async ({ email }: { email: string }) => {
      try {
        return await sendSignInLinkToEmail(ui, email);
      } catch (error) {
        if (error instanceof FirebaseUIError) {
          throw new Error(error.message);
        }

        console.error(error);
        throw new Error(getTranslation(ui, "errors", "unknownError"));
      }
    },
    [ui]
  );
}

export function useEmailLinkAuthForm(onSuccess?: EmailLinkAuthFormProps["onEmailSent"]) {
  const schema = useEmailLinkAuthFormSchema();
  const action = useEmailLinkAuthFormAction();

  return form.useAppForm({
    defaultValues: {
      email: "",
    },
    validators: {
      onBlur: schema,
      onSubmit: schema,
      onSubmitAsync: async ({ value }) => {
        try {
          await action(value);
          return onSuccess?.();
        } catch (error) {
          return error instanceof Error ? error.message : String(error);
        }
      },
    },
  });
}

export function useEmailLinkAuthFormCompleteSignIn(onSignIn?: EmailLinkAuthFormProps["onSignIn"]) {
  const ui = useUI();

  useEffect(() => {
    const completeSignIn = async () => {
      const credential = await completeEmailLinkSignIn(ui, window.location.href);

      if (credential) {
        onSignIn?.(credential);
      }
    };

    void completeSignIn();
  }, [ui, onSignIn]);
}

export function EmailLinkAuthForm({ onEmailSent, onSignIn }: EmailLinkAuthFormProps) {
  const ui = useUI();
  const [emailSent, setEmailSent] = useState(false);

  const form = useEmailLinkAuthForm(() => {
    setEmailSent(true);
    onEmailSent?.();
  });

  useEmailLinkAuthFormCompleteSignIn(onSignIn);

  if (emailSent) {
    return <div className="fui-success">{getTranslation(ui, "messages", "signInLinkSent")}</div>;
  }

  return (
    <form
      className="fui-form"
      onSubmit={async (e) => {
        e.preventDefault();
        e.stopPropagation();
        await form.handleSubmit();
      }}
    >
      <form.AppForm>
        <fieldset>
          <form.AppField name="email">{(field) => <field.Input label="Email" type="email" />}</form.AppField>
        </fieldset>
        <Policies />
        <fieldset>
          <form.SubmitButton>{getTranslation(ui, "labels", "sendSignInLink")}</form.SubmitButton>
          <form.ErrorMessage />
        </fieldset>
      </form.AppForm>
    </form>
  );
}
