// packages/angular/src/lib/auth/forms/forgot-password-auth-form.ts
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, effect, output, signal } from "@angular/core";
import { CommonModule } from "@angular/common";
import { injectForm, injectStore, TanStackAppField, TanStackField } from "@tanstack/angular-form";
import { FirebaseUIError, sendPasswordResetEmail } from "@firebase-oss/ui-core";

import {
  FormInputComponent,
  FormSubmitComponent,
  FormErrorMessageComponent,
  FormActionComponent,
} from "../../components/form";
import { PoliciesComponent } from "../../components/policies";
import { injectForgotPasswordAuthFormSchema, injectTranslation, injectUI } from "../../provider";

@Component({
  selector: "fui-forgot-password-auth-form",
  standalone: true,
  imports: [
    CommonModule,
    TanStackField,
    TanStackAppField,
    PoliciesComponent,
    FormInputComponent,
    FormSubmitComponent,
    FormErrorMessageComponent,
    FormActionComponent,
  ],
  template: `
    @if (emailSent()) {
      <div class="fui-form__success">
        {{ checkEmailForResetMessage() }}
      </div>
    }

    @if (!emailSent()) {
      <form (submit)="handleSubmit($event)" class="fui-form">
        <fieldset>
          <fui-form-input name="email" tanstack-app-field [tanstackField]="form" label="{{ emailLabel() }}" />
        </fieldset>

        <fui-policies />

        <fieldset>
          <fui-form-submit [state]="state()">
            {{ resetPasswordLabel() }}
          </fui-form-submit>
          <fui-form-error-message [state]="state()" />
        </fieldset>

        @if (backToSignIn) {
          <button fui-form-action (click)="backToSignIn.emit()">{{ backToSignInLabel() }} &rarr;</button>
        }
      </form>
    }
  `,
})
export class ForgotPasswordAuthFormComponent {
  private ui = injectUI();
  private formSchema = injectForgotPasswordAuthFormSchema();

  emailSent = signal<boolean>(false);

  emailLabel = injectTranslation("labels", "emailAddress");
  resetPasswordLabel = injectTranslation("labels", "resetPassword");
  backToSignInLabel = injectTranslation("labels", "backToSignIn");
  checkEmailForResetMessage = injectTranslation("messages", "checkEmailForReset");
  unknownErrorLabel = injectTranslation("errors", "unknownError");

  passwordSent = output<void>();
  backToSignIn = output<void>();

  form = injectForm({
    defaultValues: {
      email: "",
    },
  });

  state = injectStore(this.form, (state) => state);

  async handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    event.stopPropagation();
    this.form.handleSubmit();
  }

  constructor() {
    effect(() => {
      this.form.update({
        validators: {
          onBlur: this.formSchema(),
          onSubmit: this.formSchema(),
          onSubmitAsync: async ({ value }) => {
            try {
              await sendPasswordResetEmail(this.ui(), value.email);
              this.emailSent.set(true);
              this.passwordSent?.emit();
              return;
            } catch (error) {
              if (error instanceof FirebaseUIError) {
                return error.message;
              }

              return this.unknownErrorLabel();
            }
          },
        },
      });
    });
  }
}

// packages/react/src/auth/forms/forgot-password-auth-form.tsx
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

"use client";

import { FirebaseUIError, getTranslation, sendPasswordResetEmail } from "@firebase-oss/ui-core";
import { useForgotPasswordAuthFormSchema, useUI } from "~/hooks";
import { form } from "~/components/form";
import { Policies } from "~/components/policies";
import { useCallback, useState } from "react";

export type ForgotPasswordAuthFormProps = {
  onPasswordSent?: () => void;
  onBackToSignInClick?: () => void;
};

export function useForgotPasswordAuthFormAction() {
  const ui = useUI();

  return useCallback(
    async ({ email }: { email: string }) => {
      try {
        return await sendPasswordResetEmail(ui, email);
      } catch (error) {
        if (error instanceof FirebaseUIError) {
          throw new Error(error.message);
        }

        console.error(error);
        throw new Error(getTranslation(ui, "errors", "unknownError"));
      }
    },
    [ui]
  );
}

export function useForgotPasswordAuthForm(onSuccess?: ForgotPasswordAuthFormProps["onPasswordSent"]) {
  const schema = useForgotPasswordAuthFormSchema();
  const action = useForgotPasswordAuthFormAction();

  return form.useAppForm({
    defaultValues: {
      email: "",
    },
    validators: {
      onBlur: schema,
      onSubmit: schema,
      onSubmitAsync: async ({ value }) => {
        try {
          await action(value);
          return onSuccess?.();
        } catch (error) {
          return error instanceof Error ? error.message : String(error);
        }
      },
    },
  });
}

export function ForgotPasswordAuthForm({ onBackToSignInClick, onPasswordSent }: ForgotPasswordAuthFormProps) {
  const ui = useUI();
  const [emailSent, setEmailSent] = useState(false);
  const form = useForgotPasswordAuthForm(() => {
    setEmailSent(true);
    onPasswordSent?.();
  });

  if (emailSent) {
    return <div className="fui-success">{getTranslation(ui, "messages", "checkEmailForReset")}</div>;
  }

  return (
    <form
      className="fui-form"
      onSubmit={async (e) => {
        e.preventDefault();
        e.stopPropagation();
        await form.handleSubmit();
      }}
    >
      <form.AppForm>
        <fieldset>
          <form.AppField name="email">
            {(field) => <field.Input label={getTranslation(ui, "labels", "emailAddress")} type="email" />}
          </form.AppField>
        </fieldset>
        <Policies />
        <fieldset>
          <form.SubmitButton>{getTranslation(ui, "labels", "resetPassword")}</form.SubmitButton>
          <form.ErrorMessage />
        </fieldset>
        {onBackToSignInClick ? (
          <form.Action onClick={onBackToSignInClick}>{getTranslation(ui, "labels", "backToSignIn")}</form.Action>
        ) : null}
      </form.AppForm>
    </form>
  );
}
