// packages/angular/src/lib/auth/forms/multi-factor-auth-assertion-form.ts
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, computed, effect, output, signal } from "@angular/core";
import { CommonModule } from "@angular/common";
import { injectUI, injectTranslation } from "../../provider";
import {
  PhoneMultiFactorGenerator,
  TotpMultiFactorGenerator,
  type UserCredential,
  type MultiFactorInfo,
} from "firebase/auth";
import { SmsMultiFactorAssertionFormComponent } from "./mfa/sms-multi-factor-assertion-form";
import { TotpMultiFactorAssertionFormComponent } from "./mfa/totp-multi-factor-assertion-form";
import { ButtonComponent } from "../../components/button";

@Component({
  selector: "fui-multi-factor-auth-assertion-form",
  standalone: true,
  imports: [CommonModule, SmsMultiFactorAssertionFormComponent, TotpMultiFactorAssertionFormComponent, ButtonComponent],
  template: `
    <div class="fui-content">
      @if (selectedHint()) {
        @if (selectedHint()!.factorId === phoneFactorId) {
          <fui-sms-multi-factor-assertion-form [hint]="selectedHint()!" (onSuccess)="onSuccess.emit($event)" />
        } @else if (selectedHint()!.factorId === totpFactorId) {
          <fui-totp-multi-factor-assertion-form [hint]="selectedHint()!" (onSuccess)="onSuccess.emit($event)" />
        }
      } @else {
        <p>{{ mfaAssertionFactorPrompt() }}</p>
        @for (hint of resolver().hints; track hint.factorId) {
          @if (hint.factorId === totpFactorId) {
            <button fui-button (click)="selectHint(hint)">
              {{ totpVerificationLabel() }}
            </button>
          } @else if (hint.factorId === phoneFactorId) {
            <button fui-button (click)="selectHint(hint)">
              {{ smsVerificationLabel() }}
            </button>
          }
        }
      }
    </div>
  `,
})
export class MultiFactorAuthAssertionFormComponent {
  private ui = injectUI();

  constructor() {
    effect((onCleanup) => {
      // Cleanup the multi-factor resolver when the component unmounts.
      onCleanup(() => {
        this.ui().setMultiFactorResolver();
      });
    });
  }

  onSuccess = output<UserCredential>();

  resolver = computed(() => {
    const resolver = this.ui().multiFactorResolver;
    if (!resolver) {
      throw new Error("MultiFactorAuthAssertionForm requires a multi-factor resolver");
    }
    return resolver;
  });

  selectedHint = signal<MultiFactorInfo | undefined>(
    this.resolver().hints.length === 1 ? this.resolver().hints[0] : undefined
  );

  phoneFactorId = PhoneMultiFactorGenerator.FACTOR_ID;
  totpFactorId = TotpMultiFactorGenerator.FACTOR_ID;

  smsVerificationLabel = injectTranslation("labels", "mfaSmsVerification");
  totpVerificationLabel = injectTranslation("labels", "mfaTotpVerification");
  mfaAssertionFactorPrompt = injectTranslation("prompts", "mfaAssertionFactorPrompt");

  selectHint(hint: MultiFactorInfo) {
    this.selectedHint.set(hint);
  }
}

// packages/react/src/auth/forms/multi-factor-auth-assertion-form.tsx
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {
  PhoneMultiFactorGenerator,
  TotpMultiFactorGenerator,
  type UserCredential,
  type MultiFactorInfo,
} from "firebase/auth";
import { type ComponentProps, useEffect, useState } from "react";
import { useUI } from "~/hooks";
import { TotpMultiFactorAssertionForm } from "../forms/mfa/totp-multi-factor-assertion-form";
import { SmsMultiFactorAssertionForm } from "../forms/mfa/sms-multi-factor-assertion-form";
import { Button } from "~/components/button";
import { getTranslation } from "@firebase-oss/ui-core";

/** Props for the MultiFactorAuthAssertionForm component. */
export type MultiFactorAuthAssertionFormProps = {
  /** Optional callback function called when multi-factor assertion is successful. */
  onSuccess?: (credential: UserCredential) => void;
};

/**
 * Hook that cleans up the multi-factor resolver when the component unmounts.
 *
 * Ensures the resolver is cleared from the UI state to prevent stale state.
 */
export function useMultiFactorAssertionCleanup() {
  const ui = useUI();

  useEffect(() => {
    return () => {
      ui.setMultiFactorResolver();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps -- UI isn't stable enough to be a dependency here. Could we use useEffectEvent here instead once we depend on 19.2?
  }, []);
}

/**
 * A form component for multi-factor authentication assertion.
 *
 * Displays the appropriate MFA form (SMS or TOTP) based on the available hints.
 * If only one hint is available, it is automatically selected.
 *
 * @returns The multi-factor auth assertion form component.
 * @throws {Error} Throws an error if no multi-factor resolver is available.
 */
export function MultiFactorAuthAssertionForm(props: MultiFactorAuthAssertionFormProps) {
  const ui = useUI();
  const resolver = ui.multiFactorResolver;
  const mfaAssertionFactorPrompt = getTranslation(ui, "prompts", "mfaAssertionFactorPrompt");

  useMultiFactorAssertionCleanup();

  if (!resolver) {
    throw new Error("MultiFactorAuthAssertionForm requires a multi-factor resolver");
  }

  // If only a single hint is provided, select it by default to improve UX.
  const [hint, setHint] = useState<MultiFactorInfo | undefined>(
    resolver.hints.length === 1 ? resolver.hints[0] : undefined
  );

  if (hint) {
    if (hint.factorId === PhoneMultiFactorGenerator.FACTOR_ID) {
      return (
        <SmsMultiFactorAssertionForm
          hint={hint}
          onSuccess={(credential) => {
            props.onSuccess?.(credential);
          }}
        />
      );
    }

    if (hint.factorId === TotpMultiFactorGenerator.FACTOR_ID) {
      return (
        <TotpMultiFactorAssertionForm
          hint={hint}
          onSuccess={(credential) => {
            props.onSuccess?.(credential);
          }}
        />
      );
    }
  }

  return (
    <div className="fui-content">
      <p>{mfaAssertionFactorPrompt}</p>
      {resolver.hints.map((hint) => {
        if (hint.factorId === TotpMultiFactorGenerator.FACTOR_ID) {
          return <TotpButton key={hint.factorId} onClick={() => setHint(hint)} />;
        }

        if (hint.factorId === PhoneMultiFactorGenerator.FACTOR_ID) {
          return <SmsButton key={hint.factorId} onClick={() => setHint(hint)} />;
        }

        return null;
      })}
    </div>
  );
}

function TotpButton(props: ComponentProps<typeof Button>) {
  const ui = useUI();
  const labelText = getTranslation(ui, "labels", "mfaTotpVerification");
  return <Button {...props}>{labelText}</Button>;
}

function SmsButton(props: ComponentProps<typeof Button>) {
  const ui = useUI();
  const labelText = getTranslation(ui, "labels", "mfaSmsVerification");
  return <Button {...props}>{labelText}</Button>;
}
