// packages/angular/src/lib/auth/forms/phone-auth-form/phone-auth-form.component.ts
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {
  Component,
  ElementRef,
  effect,
  input,
  signal,
  output,
  computed,
  viewChild,
} from "@angular/core";
import { CommonModule } from "@angular/common";
import { injectForm, injectStore, TanStackAppField, TanStackField } from "@tanstack/angular-form";
import { injectPhoneAuthFormSchema, injectPhoneAuthVerifyFormSchema, injectTranslation, injectUI } from "../../../provider";
import { RecaptchaVerifier, UserCredential } from "@angular/fire/auth";
import { PoliciesComponent } from "../../../components/policies/policies.component";
import { CountrySelectorComponent } from "../../../components/country-selector/country-selector.component";
import {
  FormInputComponent,
  FormSubmitComponent,
  FormErrorMessageComponent,
} from "../../../components/form/form.component";
import {
  countryData,
  FirebaseUIError,
  formatPhoneNumber,
  confirmPhoneNumber,
  verifyPhoneNumber,
  CountryCode,
} from "@firebase-ui/core";

@Component({
  selector: "fui-phone-number-form",
  standalone: true,
  imports: [
    CommonModule,
    TanStackField,
    TanStackAppField,
    PoliciesComponent,
    FormInputComponent,
    FormSubmitComponent,
    FormErrorMessageComponent,
    CountrySelectorComponent,
  ],
  template: `
    <form (submit)="handleSubmit($event)" class="fui-form">
      <fieldset>
        <fui-country-selector [(value)]="country"></fui-country-selector>
        <fui-form-input
          name="phoneNumber"
          tanstack-app-field
          [tanstackField]="form"
          label="{{ phoneNumberLabel() }}"
        ></fui-form-input>
      </fieldset>
      <fieldset>
        <div class="fui-recaptcha-container" #recaptchaContainer></div>
      </fieldset>
      <fui-policies />
      <fieldset>
        <fui-form-submit [state]="state()">
          {{ sendCodeLabel() }}
        </fui-form-submit>
        <fui-form-error-message [state]="state()" />
      </fieldset>
    </form>
  `,
})
export class PhoneNumberFormComponent {
  private ui = injectUI();
  private formSchema = injectPhoneAuthFormSchema();

  onSubmit = output<{ verificationId: string; phoneNumber: string }>();
  country = signal<CountryCode>(countryData[0].code);

  phoneNumberLabel = injectTranslation("labels", "phoneNumber");
  sendCodeLabel = injectTranslation("labels", "sendCode");
  unknownErrorLabel = injectTranslation("errors", "unknownError");

  recaptchaContainer = viewChild.required<ElementRef<HTMLDivElement>>("recaptchaContainer");

  recaptchaVerifier = computed(() => {
    return new RecaptchaVerifier(this.ui().auth, this.recaptchaContainer().nativeElement, {
      size: "normal", // TODO(ehesp): Get this from the ui behavior
    });
  });

  form = injectForm({
    defaultValues: {
      phoneNumber: "",
    },
  });

  state = injectStore(this.form, (state) => state);

  constructor() {
    effect(() => {
      this.form.update({
        validators: {
          onBlur: this.formSchema(),
          onSubmit: this.formSchema(),
          onSubmitAsync: async ({ value }) => {
            const selectedCountry = countryData.find(c => c.code === this.country());
            const formattedNumber = formatPhoneNumber(value.phoneNumber, selectedCountry!);

            try {
              const verificationId = await verifyPhoneNumber(this.ui(), formattedNumber, this.recaptchaVerifier());
              this.onSubmit.emit({ verificationId, phoneNumber: formattedNumber });
              return;
            } catch (error) {
              if (error instanceof FirebaseUIError) {
                return error.message;
              }

              return this.unknownErrorLabel();
            }
          },
        },
      });
    });

    effect((onCleanup) => {
      const verifier = this.recaptchaVerifier();

      onCleanup(() => {
        verifier.clear();
      });
    });
  }


  async handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    event.stopPropagation();
    this.form.handleSubmit();
  }
}

@Component({
  selector: "fui-verification-form",
  standalone: true,
  imports: [
    CommonModule,
    TanStackField,
    TanStackAppField,
    PoliciesComponent,
    FormInputComponent,
    FormSubmitComponent,
    FormErrorMessageComponent,
  ],
  template: `
    <form (submit)="handleSubmit($event)" class="fui-form">
      <fieldset>
        <fui-form-input
          name="verificationCode"
          tanstack-app-field
          [tanstackField]="form"
          label="{{ verificationCodeLabel() }}"
        ></fui-form-input>
      </fieldset>

      <fui-policies />

      <fieldset>
        <fui-form-submit [state]="state()">
          {{ verifyCodeLabel() }}
        </fui-form-submit>
        <fui-form-error-message [state]="state()" />
      </fieldset>
    </form>
  `,
})
export class VerificationFormComponent {
  private ui = injectUI();
  private formSchema = injectPhoneAuthVerifyFormSchema();

  verificationId = input.required<string>();
  signIn = output<UserCredential>();

  verificationCodeLabel = injectTranslation("labels", "verificationCode");
  verifyCodeLabel = injectTranslation("labels", "verifyCode");
  unknownErrorLabel = injectTranslation("errors", "unknownError");


  form = injectForm({
    defaultValues: {
      verificationId: "",
      verificationCode: "",
    },
  });

  state = injectStore(this.form, (state) => state);

  constructor() {
    effect(() => {
      this.form.setFieldValue("verificationId", this.verificationId());
    });

    effect(() => {
      this.form.update({
        validators: {
          onBlur: this.formSchema(),
          onSubmit: this.formSchema(),
          onSubmitAsync: async ({ value }) => {
            try {
              const credential = await confirmPhoneNumber(this.ui(), this.verificationId(), value.verificationCode);
              this.signIn.emit(credential);
              return;
            } catch (error) {
              if (error instanceof FirebaseUIError) {
                return error.message;
              }

              return this.unknownErrorLabel();
            }
          },
        },
      });
    });
  }


  async handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    event.stopPropagation();
    this.form.handleSubmit();
  }

}

@Component({
  selector: "fui-phone-auth-form",
  standalone: true,
  imports: [CommonModule, PhoneNumberFormComponent, VerificationFormComponent],
  template: `
    <div class="fui-form-container">
      @if (verificationId()) {
        <fui-verification-form 
          [verificationId]="verificationId()!" 
          (signIn)="signIn.emit($event)" />
      } @else {
        <fui-phone-number-form (onSubmit)="handlePhoneSubmit($event)" />
      }
    </div>
  `,
})
export class PhoneAuthFormComponent {
  verificationId = signal<string | null>(null);
  signIn = output<UserCredential>();

  handlePhoneSubmit(data: { verificationId: string; phoneNumber: string }) {
    this.verificationId.set(data.verificationId);
  }
}

// packages/react/src/auth/forms/phone-auth-form.tsx
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

"use client";

import {
  CountryCode,
  countryData,
  FirebaseUIError,
  formatPhoneNumberWithCountry,
  getTranslation,
  verifyPhoneNumber,
  confirmPhoneNumber,
} from "@firebase-ui/core";
import { RecaptchaVerifier, UserCredential } from "firebase/auth";
import { useCallback, useRef, useState } from "react";
import { usePhoneAuthNumberFormSchema, usePhoneAuthVerifyFormSchema, useRecaptchaVerifier, useUI } from "~/hooks";
import { form } from "~/components/form";
import { Policies } from "~/components/policies";
import { CountrySelector } from "~/components/country-selector";

export function usePhoneNumberFormAction() {
  const ui = useUI();

  return useCallback(
    async ({ phoneNumber, recaptchaVerifier }: { phoneNumber: string; recaptchaVerifier: RecaptchaVerifier }) => {
      return await verifyPhoneNumber(ui, phoneNumber, recaptchaVerifier);
    },
    [ui]
  );
}

type UsePhoneNumberForm = {
  recaptchaVerifier: RecaptchaVerifier;
  onSuccess: (verificationId: string) => void;
  formatPhoneNumber?: (phoneNumber: string) => string;
};

export function usePhoneNumberForm({ recaptchaVerifier, onSuccess, formatPhoneNumber }: UsePhoneNumberForm) {
  const action = usePhoneNumberFormAction();
  const schema = usePhoneAuthNumberFormSchema();

  return form.useAppForm({
    defaultValues: {
      phoneNumber: "",
    },
    validators: {
      onBlur: schema,
      onSubmit: schema,
      onSubmitAsync: async ({ value }) => {
        try {
          const formatted = formatPhoneNumber ? formatPhoneNumber(value.phoneNumber) : value.phoneNumber;
          const confirmationResult = await action({ phoneNumber: formatted, recaptchaVerifier });
          return onSuccess(confirmationResult);
        } catch (error) {
          return error instanceof FirebaseUIError ? error.message : String(error);
        }
      },
    },
  });
}

type PhoneNumberFormProps = {
  onSubmit: (verificationId: string) => void;
};

export function PhoneNumberForm(props: PhoneNumberFormProps) {
  const ui = useUI();
  const recaptchaContainerRef = useRef<HTMLDivElement>(null);
  const recaptchaVerifier = useRecaptchaVerifier(recaptchaContainerRef);
  const form = usePhoneNumberForm({
    recaptchaVerifier: recaptchaVerifier!,
    onSuccess: props.onSubmit,
    formatPhoneNumber: (phoneNumber) => formatPhoneNumberWithCountry(phoneNumber, selectedCountry),
  });

  const [selectedCountry, setSelectedCountry] = useState<CountryCode>(countryData[0].code);

  return (
    <form
      className="fui-form"
      onSubmit={async (e) => {
        e.preventDefault();
        e.stopPropagation();
        await form.handleSubmit();
      }}
    >
      <form.AppForm>
        <fieldset>
          <form.AppField name="phoneNumber">
            {(field) => (
              <field.Input
                label={getTranslation(ui, "labels", "phoneNumber")}
                type="tel"
                before={
                  <CountrySelector
                    value={selectedCountry}
                    onChange={(code) => setSelectedCountry(code as CountryCode)}
                    className="fui-phone-input__country-selector"
                  />
                }
              />
            )}
          </form.AppField>
        </fieldset>
        <fieldset>
          <div className="fui-recaptcha-container" ref={recaptchaContainerRef} />
        </fieldset>
        <Policies />
        <fieldset>
          <form.SubmitButton>{getTranslation(ui, "labels", "sendCode")}</form.SubmitButton>
          <form.ErrorMessage />
        </fieldset>
      </form.AppForm>
    </form>
  );
}

export function useVerifyPhoneNumberFormAction() {
  const ui = useUI();

  return useCallback(
    async ({ verificationId, verificationCode }: { verificationId: string; verificationCode: string }) => {
      return await confirmPhoneNumber(ui, verificationId, verificationCode);
    },
    [ui]
  );
}

type UseVerifyPhoneNumberForm = {
  verificationId: string;
  onSuccess: (credential: UserCredential) => void;
};

export function useVerifyPhoneNumberForm({ verificationId, onSuccess }: UseVerifyPhoneNumberForm) {
  const schema = usePhoneAuthVerifyFormSchema();
  const action = useVerifyPhoneNumberFormAction();

  return form.useAppForm({
    defaultValues: {
      verificationId,
      verificationCode: "",
    },
    validators: {
      onSubmit: schema,
      onBlur: schema,
      onSubmitAsync: async ({ value }) => {
        try {
          const credential = await action(value);
          return onSuccess(credential);
        } catch (error) {
          return error instanceof FirebaseUIError ? error.message : String(error);
        }
      },
    },
  });
}

type VerifyPhoneNumberFormProps = {
  onSuccess: (credential: UserCredential) => void;
  verificationId: string;
};

function VerifyPhoneNumberForm(props: VerifyPhoneNumberFormProps) {
  const ui = useUI();
  const form = useVerifyPhoneNumberForm({ verificationId: props.verificationId, onSuccess: props.onSuccess });

  return (
    <form
      className="fui-form"
      onSubmit={async (e) => {
        e.preventDefault();
        e.stopPropagation();
        await form.handleSubmit();
      }}
    >
      <form.AppForm>
        <fieldset>
          <form.AppField name="verificationCode">
            {(field) => <field.Input label={getTranslation(ui, "labels", "verificationCode")} type="text" />}
          </form.AppField>
        </fieldset>
        <fieldset>
          <form.SubmitButton>{getTranslation(ui, "labels", "verifyCode")}</form.SubmitButton>
          <form.ErrorMessage />
        </fieldset>
      </form.AppForm>
    </form>
  );
}

export type PhoneAuthFormProps = {
  onSignIn?: (credential: UserCredential) => void;
};

export function PhoneAuthForm(props: PhoneAuthFormProps) {
  const [verificationId, setVerificationId] = useState<string | null>(null);

  if (!verificationId) {
    return <PhoneNumberForm onSubmit={setVerificationId} />;
  }

  return (
    <VerifyPhoneNumberForm
      verificationId={verificationId}
      onSuccess={(credential) => {
        props.onSignIn?.(credential);
      }}
    />
  );
}
