// packages/angular/src/lib/auth/forms/sign-up-auth-form/sign-up-auth-form.component.ts
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, OnInit, output } from "@angular/core";
import { CommonModule } from "@angular/common";
import { injectForm, TanStackAppField, TanStackField } from "@tanstack/angular-form";
import { FirebaseUIError, createUserWithEmailAndPassword } from "@firebase-ui/core";
import { UserCredential } from "@angular/fire/auth";

import { PoliciesComponent } from "../../../components/policies/policies.component";
import { injectSignUpAuthFormSchema, injectTranslation, injectUI } from "../../../provider";
import {
  FormInputComponent,
  FormSubmitComponent,
  FormErrorMessageComponent,
} from "../../../components/form/form.component";

@Component({
  selector: "fui-sign-up-auth-form",
  imports: [
    CommonModule,
    TanStackField,
    TanStackAppField,
    PoliciesComponent,
    FormInputComponent,
    FormSubmitComponent,
    FormErrorMessageComponent,
  ],
  template: `
    <form (submit)="handleSubmit($event)" class="fui-form">
      <fieldset>
        <fui-form-input
          name="email"
          tanstack-app-field
          [tanstackField]="form"
          label="{{ emailLabel() }}"
        ></fui-form-input>
      </fieldset>
      <fieldset>
        <fui-form-input
          name="password"
          tanstack-app-field
          [tanstackField]="form"
          label="{{ passwordLabel() }}"
        ></fui-form-input>
      </fieldset>

      <fui-policies />

      <fieldset>
        <fui-form-submit>
          {{ createAccountLabel() }}
        </fui-form-submit>
        <fui-form-error-message></fui-form-error-message>
      </fieldset>

      @if (signIn) {
        <button fui-form-action (click)="signIn.emit()">{{ haveAccountLabel() }} {{ signInLabel() }} &rarr;</button>
      }
    </form>
  `,
  standalone: true,
})
export class SignUpAuthFormComponent implements OnInit {
  private ui = injectUI();
  private formSchema = injectSignUpAuthFormSchema();

  emailLabel = injectTranslation("labels", "emailAddress");
  passwordLabel = injectTranslation("labels", "password");
  createAccountLabel = injectTranslation("labels", "createAccount");
  haveAccountLabel = injectTranslation("prompts", "haveAccount");
  signInLabel = injectTranslation("labels", "signIn");
  unknownErrorLabel = injectTranslation("errors", "unknownError");

  signUp = output<UserCredential>();
  signIn = output<void>();

  form = injectForm({
    defaultValues: {
      email: "",
      password: "",
    },
  });

  handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    event.stopPropagation();
    this.form.handleSubmit();
  }

  ngOnInit() {
    this.form.update({
      validators: {
        onBlur: this.formSchema(),
        onSubmit: this.formSchema(),
        onSubmitAsync: async ({ value }) => {
          try {
            const credential = await createUserWithEmailAndPassword(this.ui(), value.email, value.password);
            this.signUp?.emit(credential);
          } catch (error) {
            if (error instanceof FirebaseUIError) {
              return error.message;
            }

            return this.unknownErrorLabel();
          }
        },
      },
    });
  }
}

// packages/react/src/auth/forms/sign-up-auth-form.tsx
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

"use client";

import { FirebaseUIError, getTranslation, createUserWithEmailAndPassword } from "@firebase-ui/core";
import type { UserCredential } from "firebase/auth";
import { useSignUpAuthFormSchema, useUI } from "~/hooks";
import { form } from "~/components/form";
import { Policies } from "~/components/policies";
import { useCallback } from "react";

export type SignUpAuthFormProps = {
  onSignUp?: (credential: UserCredential) => void;
  onBackToSignInClick?: () => void;
};

export function useSignUpAuthFormAction() {
  const ui = useUI();

  return useCallback(
    async ({ email, password }: { email: string; password: string }) => {
      try {
        return await createUserWithEmailAndPassword(ui, email, password);
      } catch (error) {
        if (error instanceof FirebaseUIError) {
          throw new Error(error.message);
        }

        console.error(error);
        throw new Error(getTranslation(ui, "errors", "unknownError"));
      }
    },
    [ui]
  );
}

export function useSignUpAuthForm(onSuccess?: SignUpAuthFormProps["onSignUp"]) {
  const schema = useSignUpAuthFormSchema();
  const action = useSignUpAuthFormAction();

  return form.useAppForm({
    defaultValues: {
      email: "",
      password: "",
    },
    validators: {
      onBlur: schema,
      onSubmit: schema,
      onSubmitAsync: async ({ value }) => {
        try {
          const credential = await action(value);
          onSuccess?.(credential);
        } catch (error) {
          return error instanceof Error ? error.message : String(error);
        }
      },
    },
  });
}

export function SignUpAuthForm({ onBackToSignInClick, onSignUp }: SignUpAuthFormProps) {
  const ui = useUI();
  const form = useSignUpAuthForm(onSignUp);

  return (
    <form
      className="fui-form"
      onSubmit={async (e) => {
        e.preventDefault();
        e.stopPropagation();
        await form.handleSubmit();
      }}
    >
      <form.AppForm>
        <fieldset>
          <form.AppField name="email" children={(field) => <field.Input label="Email" type="email" />} />
        </fieldset>
        <fieldset>
          <form.AppField name="password" children={(field) => <field.Input label="Password" type="password" />} />
        </fieldset>
        <Policies />
        <fieldset>
          <form.SubmitButton>
            {getTranslation(ui, "labels", "createAccount")}
          </form.SubmitButton>
          <form.ErrorMessage />
        </fieldset>
        {onBackToSignInClick ? (
          <form.Action onClick={onBackToSignInClick}>
            {getTranslation(ui, "prompts", "haveAccount")} {getTranslation(ui, "labels", "signIn")}
          </form.Action>
        ) : null}
      </form.AppForm>
    </form>
  );
}
