// packages/react/src/components/form.tsx
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { type ComponentProps, type PropsWithChildren, type ReactNode } from "react";
import { type AnyFieldApi, createFormHook, createFormHookContexts } from "@tanstack/react-form";
import { Button } from "./button";
import { cn } from "~/utils/cn";

const { fieldContext, useFieldContext, formContext, useFormContext } = createFormHookContexts();

function FieldMetadata({ className, ...props }: ComponentProps<"div"> & { field: AnyFieldApi }) {
  if (!props.field.state.meta.isTouched || !props.field.state.meta.errors.length) {
    return null;
  }

  return (
    <div role="alert" aria-live="polite" className={cn("fui-error", className)} {...props}>
      {props.field.state.meta.errors.map((error) => error.message).join(", ")}
    </div>
  );
}

function Input({
  children,
  before,
  label,
  action,
  description,
  ...props
}: PropsWithChildren<
  ComponentProps<"input"> & { label: string; before?: ReactNode; action?: ReactNode; description?: ReactNode }
>) {
  const field = useFieldContext<string>();
  const form = useFormContext();

  return (
    <label htmlFor={field.name}>
      <div data-input-label>
        <div>{label}</div>
        {action ? <div>{action}</div> : null}
      </div>
      {description ? <div data-input-description>{description}</div> : null}
      <div data-input-group>
        {before}
        <input
          {...props}
          aria-invalid={field.state.meta.isTouched && field.state.meta.errors.length > 0}
          id={field.name}
          name={field.name}
          value={field.state.value}
          onChange={(e) => {
            field.handleChange(e.target.value);
            // Clear form-level submission errors when user starts typing
            const errorMap = form.state.errorMap;
            if (errorMap?.onSubmit) {
              form.setErrorMap({});
            }
          }}
        />
      </div>
      {children ? <>{children}</> : null}
      <FieldMetadata field={field} />
    </label>
  );
}

function Action({ className, ...props }: ComponentProps<"button">) {
  return <button type="button" {...props} className={cn("fui-form__action", className)} />;
}

function SubmitButton(props: ComponentProps<"button">) {
  const form = useFormContext();

  return (
    <form.Subscribe selector={(state) => state.isSubmitting}>
      {(isSubmitting) => <Button {...props} type="submit" disabled={isSubmitting} />}
    </form.Subscribe>
  );
}

function ErrorMessage() {
  const form = useFormContext();

  return (
    <form.Subscribe selector={(state) => [state.errorMap]}>
      {([errorMap]) => {
        // We only care about errors thrown from the form submission, rather than validation errors
        if (errorMap?.onSubmit && typeof errorMap.onSubmit === "string") {
          return <div className="fui-error">{errorMap.onSubmit}</div>;
        }

        return null;
      }}
    </form.Subscribe>
  );
}

/**
 * A form hook factory for creating forms with validation and error handling.
 *
 * Provides field components (Input) and form components (SubmitButton, ErrorMessage, Action)
 * for building accessible forms with TanStack Form.
 */
export const form = createFormHook({
  fieldComponents: {
    Input,
  },
  formComponents: {
    SubmitButton,
    ErrorMessage,
    Action,
  },
  fieldContext,
  formContext,
});

// packages/angular/src/lib/components/form.ts
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { ChangeDetectorRef, Component, computed, inject, input, OnChanges, SimpleChanges } from "@angular/core";
import { AnyFormState, injectField } from "@tanstack/angular-form";
import { ButtonComponent } from "./button";

@Component({
  selector: "fui-form-metadata",
  standalone: true,
  host: {
    style: "display: block;",
  },
  template: `
    @if (isTouched() && errors().length > 0) {
      <div>
        <div role="alert" aria-live="polite" class="fui-error">
          {{ errorMessage() }}
        </div>
      </div>
    }
  `,
})
/**
 * A component that displays form field metadata, such as validation errors.
 */
export class FormMetadataComponent {
  isTouched = input.required<boolean>();
  errors = input.required<Array<{ message: string }>>();

  errorMessage(): string {
    return this.errors()
      .map((error) => error.message)
      .join(", ");
  }
}

@Component({
  selector: "fui-form-input",
  standalone: true,
  imports: [FormMetadataComponent],
  host: {
    style: "display: block;",
  },
  template: `
    <label [for]="field.api.name">
      <div data-input-label>
        <div>{{ label() }}</div>
        <div><ng-content select="input-action" /></div>
      </div>
      @if (description()) {
        <div data-input-description>{{ description() }}</div>
      }
      <div data-input-group>
        <ng-content select="input-before" />
        <input
          [attr.aria-invalid]="field.api.state.meta.isTouched && field.api.state.meta.errors.length > 0"
          [id]="field.api.name"
          [name]="field.api.name"
          [value]="field.api.state.value"
          (input)="handleInput($event)"
          [type]="type()"
          [attr.autocomplete]="autocomplete()"
        />
      </div>
      <ng-content></ng-content>
      <fui-form-metadata
        [isTouched]="field.api.state.meta.isTouched"
        [errors]="field.api.state.meta.errors"
      ></fui-form-metadata>
    </label>
  `,
})
/**
 * A form input component with label, description, and validation support.
 */
export class FormInputComponent implements OnChanges {
  field = injectField<string>();
  private cdr = inject(ChangeDetectorRef);
  /** The label text for the input field. */
  label = input.required<string>();
  /** The input type (e.g., "text", "email", "password"). */
  type = input<string>("text");
  /** Optional description text displayed below the label. */
  description = input<string>();
  /** The autocomplete hint forwarded to the underlying input (e.g. "username", "current-password"). */
  autocomplete = input<string>();

  handleInput(event: Event) {
    const value = (event.target as HTMLInputElement | null)?.value ?? "";
    this.field.api.handleChange(value);

    // Clear form-level submission errors when user starts typing
    const form = (this.field.api as any)?.form;
    const errorMap = form?.state?.errorMap;
    if (errorMap?.onSubmit) {
      form?.setErrorMap?.({});
    }
  }

  ngOnChanges(_changes: SimpleChanges): void {
    // Trigger change detection when any input changes
    this.cdr.markForCheck();
  }
}

@Component({
  selector: "button[fui-form-action]",
  standalone: true,
  host: {
    class: "fui-form__action",
    type: "button",
  },
  template: `<ng-content></ng-content> `,
})
/**
 * A button component for form actions (e.g., "Forgot Password?" link).
 */
export class FormActionComponent {}

@Component({
  selector: "fui-form-submit",
  standalone: true,
  imports: [ButtonComponent],
  host: {
    type: "submit",
    style: "display: block;",
  },
  template: `
    <button fui-button class="fui-form__action" [class]="class()" [disabled]="isDisabled()">
      <ng-content></ng-content>
    </button>
  `,
})
/**
 * A submit button component for forms.
 *
 * Automatically disables when the form is submitting.
 */
export class FormSubmitComponent {
  /** Optional additional CSS classes. */
  class = input<string>();
  /** The form state for tracking submission status. */
  state = input.required<AnyFormState>();
  /** Optional additional disabled condition. */
  disabled = input<boolean>(false);

  isSubmitting = computed(() => this.state().isSubmitting);
  isDisabled = computed(() => this.isSubmitting() || this.disabled());
}

@Component({
  selector: "fui-form-error-message",
  standalone: true,
  host: {
    style: "display: block;",
  },
  template: `
    @if (errorMessage()) {
      <div class="fui-error">
        {{ errorMessage() }}
      </div>
    }
  `,
})
/**
 * A component that displays form-level error messages.
 *
 * Shows errors from form submission, not validation errors.
 */
export class FormErrorMessageComponent {
  /** The form state containing error information. */
  state = input.required<AnyFormState>();

  errorMessage = computed(() => {
    const error = this.state().errorMap?.onSubmit;

    // We only care about errors thrown from the form submission, rather than validation errors
    if (error && typeof error === "string") {
      return error;
    }

    return undefined;
  });
}
