// examples/react/src/screens/forgot-password-auth-screen.tsx
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

"use client";

import { ForgotPasswordAuthScreen } from "@invertase/firebaseui-react";
import { useNavigate } from "react-router";

export default function ForgotPasswordAuthScreenPage() {
  const navigate = useNavigate();

  return (
    <ForgotPasswordAuthScreen
      onBackToSignInClick={() => {
        navigate("/screens/sign-in-auth-screen");
      }}
    />
  );
}

// examples/angular/src/app/screens/forgot-password-auth-screen/forgot-password-auth-screen.component.ts
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component } from "@angular/core";
import { CommonModule } from "@angular/common";
import { ForgotPasswordAuthScreenComponent } from "@invertase/firebaseui-angular";

@Component({
  selector: "app-forgot-password-auth-screen",
  standalone: true,
  imports: [CommonModule, ForgotPasswordAuthScreenComponent],
  template: ` <fui-forgot-password-auth-screen></fui-forgot-password-auth-screen> `,
  styles: [],
})
export class ForgotPasswordAuthScreenWrapperComponent {}
