// examples/angular/src/app/app.component.ts
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Component, computed, inject, input } from "@angular/core";
import { RouterModule, Router } from "@angular/router";
import { CommonModule } from "@angular/common";
import { Auth, multiFactor, sendEmailVerification, signOut, type User } from "@angular/fire/auth";
import { routes } from "./routes";
import { ThemeToggleComponent } from "./components/theme-toggle/theme-toggle.component";
import { PirateToggleComponent } from "./components/pirate-toggle/pirate-toggle.component";
import { MultiFactorAuthAssertionScreenComponent } from "@invertase/firebaseui-angular";
import { injectUI } from "@invertase/firebaseui-angular";

@Component({
  selector: "app-unauthenticated",
  standalone: true,
  imports: [CommonModule, RouterModule, MultiFactorAuthAssertionScreenComponent],
  template: `
    @if (mfaResolver()) {
      <fui-multi-factor-auth-assertion-screen />
    } @else {
      <div class="max-w-sm mx-auto pt-36 space-y-6 pb-36">
        <div class="text-center space-y-4">
          <img
            src="/firebase-logo-inverted.png"
            alt="Firebase UI"
            class="hidden dark:block h-36 mx-auto"
          />
          <img src="/firebase-logo.png" alt="Firebase UI" class="block dark:hidden h-36 mx-auto" />
          <p class="text-sm text-gray-700 dark:text-gray-300">
            Welcome to Firebase UI, choose an example screen below to get started!
          </p>
        </div>
        <div
          class="border border-neutral-200 dark:border-neutral-800 rounded divide-y divide-neutral-200 dark:divide-neutral-800 overflow-hidden"
        >
          @for (route of routes; track route.path) {
            <a
              [routerLink]="route.path"
              class="flex items-center justify-between hover:bg-neutral-100 dark:bg-neutral-900 dark:hover:bg-neutral-800 p-4"
            >
              <div class="space-y-1">
                <h2 class="font-medium text-sm">{{ route.name }}</h2>
                <p class="text-xs text-gray-400 dark:text-gray-300">{{ route.description }}</p>
              </div>
              <div class="text-neutral-600 dark:text-neutral-400">
                <span class="text-xl">&rarr;</span>
              </div>
            </a>
          }
        </div>
      </div>
    }
  `,
})
export class UnauthenticatedAppComponent {
  ui = injectUI();
  routes = routes;

  mfaResolver = computed(() => this.ui().multiFactorResolver);
}

@Component({
  selector: "app-authenticated",
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `
    <div class="max-w-sm mx-auto pt-36 space-y-6 pb-36">
      <div class="border border-neutral-200 dark:border-neutral-800 rounded-md p-4 space-y-4">
        <h1 class="text-md font-medium">
          Welcome, {{ user().displayName || user().email || user().phoneNumber }}
        </h1>
        @if (user().email) {
          @if (user().emailVerified) {
            <div class="text-green-500">Email verified</div>
          } @else {
            <button
              class="bg-red-500 text-white px-3 py-1.5 rounded text-sm"
              (click)="verifyEmail()"
            >
              Verify Email &rarr;
            </button>
          }
        }
        <hr class="opacity-30" />
        <h2 class="text-sm font-medium">Multi-factor Authentication</h2>
        @for (factor of mfaFactors(); track factor.factorId) {
          <div>
            {{ factor.factorId }} - {{ factor.displayName }}
          </div>
        }
        <button
          class="bg-blue-500 text-white px-3 py-1.5 rounded text-sm"
          (click)="navigateToMfa()"
        >
          Add MFA Factor &rarr;
        </button>
        <hr class="opacity-30" />
        <button class="bg-blue-500 text-white px-3 py-1.5 rounded text-sm" (click)="signOut()">
          Sign Out &rarr;
        </button>
      </div>
    </div>
  `,
})
export class AuthenticatedAppComponent {
  user = input.required<User>();
  private auth = inject(Auth);
  private router = inject(Router);

  mfaFactors = computed(() => {
    const mfa = multiFactor(this.user());
    return mfa.enrolledFactors;
  });

  async verifyEmail() {
    try {
      await sendEmailVerification(this.user());
      alert("Email verification sent, please check your email");
    } catch (error) {
      console.error(error);
      alert("Error sending email verification, check console");
    }
  }

  navigateToMfa() {
    this.router.navigate(["/screens/mfa-enrollment-screen"]);
  }

  async signOut() {
    await signOut(this.auth);
  }
}

@Component({
  selector: "app-root",
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    ThemeToggleComponent,
    PirateToggleComponent,
  ],
  templateUrl: "./app.component.html",
})
export class AppComponent {}

<!--
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<app-theme-toggle />
<app-pirate-toggle />
<router-outlet />

// examples/nextjs/app/page.tsx
/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

"use client";

import { MultiFactorAuthAssertionScreen, useUI } from "@invertase/firebaseui-react";
import { multiFactor, sendEmailVerification, signOut } from "firebase/auth";
import { useRouter } from "next/navigation";
import { useUser } from "@/lib/firebase/hooks";
import { auth } from "@/lib/firebase/clientApp";
import { routes } from "@/lib/routes";
import Link from "next/link";

export default function Home() {
  const user = useUser();
  const ui = useUI();
  const router = useRouter();

  if (user) {
    return <AuthenticatedApp user={user} router={router} />;
  }

  return <UnauthenticatedApp ui={ui} />;
}

function UnauthenticatedApp({ ui }: { ui: ReturnType<typeof useUI> }) {
  // This can trigger if the user is not on a screen already, and gets an MFA challenge - e.g. on One-Tap sign in.
  if (ui.multiFactorResolver) {
    return <MultiFactorAuthAssertionScreen />;
  }

  return (
    <div className="max-w-sm mx-auto pt-36 space-y-6 pb-36">
      <div className="text-center space-y-4">
        <img src="/firebase-logo-inverted.png" alt="Firebase UI" className="hidden dark:block h-36 mx-auto" />
        <img src="/firebase-logo.png" alt="Firebase UI" className="block dark:hidden h-36 mx-auto" />
        <p className="text-sm text-gray-700 dark:text-gray-300">
          Welcome to Firebase UI, choose an example screen below to get started!
        </p>
      </div>
      <div className="border border-neutral-200 dark:border-neutral-800 rounded divide-y divide-neutral-200 dark:divide-neutral-800 overflow-hidden">
        {routes.map((route) => (
          <Link
            key={route.path}
            href={route.path}
            className="flex items-center justify-between hover:bg-neutral-100 dark:bg-neutral-900 dark:hover:bg-neutral-800 p-4"
          >
            <div className="space-y-1">
              <h2 className="font-medium text-sm">{route.name}</h2>
              <p className="text-xs text-gray-400 dark:text-gray-300">{route.description}</p>
            </div>
            <div className="text-neutral-600 dark:text-neutral-400">
              <span className="text-xl">&rarr;</span>
            </div>
          </Link>
        ))}
      </div>
    </div>
  );
}

function AuthenticatedApp({
  user,
  router,
}: {
  user: NonNullable<ReturnType<typeof useUser>>;
  router: ReturnType<typeof useRouter>;
}) {
  const mfa = multiFactor(user);

  return (
    <div className="max-w-sm mx-auto pt-36 space-y-6 pb-36">
      <div className="border border-neutral-200 dark:border-neutral-800 rounded-md p-4 space-y-4">
        <h1 className="text-md font-medium">Welcome, {user.displayName || user.email || user.phoneNumber}</h1>
        {user.email ? (
          <>
            {user.emailVerified ? (
              <div className="text-green-500">Email verified</div>
            ) : (
              <button
                className="bg-red-500 text-white px-3 py-1.5 rounded text-sm"
                onClick={async () => {
                  try {
                    await sendEmailVerification(user);
                    alert("Email verification sent, please check your email");
                  } catch (error) {
                    console.error(error);
                    alert("Error sending email verification, check console");
                  }
                }}
              >
                Verify Email &rarr;
              </button>
            )}
          </>
        ) : null}

        <hr className="opacity-30" />
        <h2 className="text-sm font-medium">Multi-factor Authentication</h2>
        {mfa.enrolledFactors.map((factor) => {
          return (
            <div key={factor.factorId}>
              {factor.factorId} - {factor.displayName}
            </div>
          );
        })}
        <button
          className="bg-blue-500 text-white px-3 py-1.5 rounded text-sm"
          onClick={() => {
            router.push("/screens/mfa-enrollment-screen");
          }}
        >
          Add MFA Factor &rarr;
        </button>
        <hr className="opacity-30" />
        <button
          className="bg-blue-500 text-white px-3 py-1.5 rounded text-sm"
          onClick={async () => await signOut(auth)}
        >
          Sign Out &rarr;
        </button>
      </div>
    </div>
  );
}
